class Autogenerated {
  int? accountId;
  int? projectTaskId;
  int? projectId;
  int? taskType;
  dynamic phaseId;
  String? taskName;
  int? taskCategory;
  dynamic estStartDate;
  dynamic estEndDate;
  String? planStartDate;
  dynamic planEndDate;
  String? actStartDate;
  String? actEndDate;
  int? taskStatus;
  int? priorityId;
  dynamic sequence;
  int? assingedTo;
  List<Collaborators>? collaborators;
  dynamic collaboratorsId;
  dynamic estEfforts;
  dynamic dueDate;
  dynamic extEfforts;
  dynamic actEfforts;
  String? startTime;
  bool? focus;
  int? invoiced;
  int? billable;
  dynamic snoozeTask;
  dynamic snoozeDate;
  String? editMode;
  int? createdBy;
  String? createdAt;
  int? updatedBy;
  String? updatedAt;
  dynamic attachment;
  dynamic taskDesc;
  dynamic refProjectTaskId;
  String? reportedDate;
  dynamic reportedTime;
  dynamic endTime;
  String? assingedName;
  String? createdName;
  String? updatedName;
  String? myEfforts;
  String? allEfforts;
  String? taskDayAgo;
  String? projectName;
  String? priorityName;
  String? taskTypeName;
  String? taskCategoryName;
  int? focusId;
  String? taskStatusGroup;
  String? status;
  int? statusGroup;
  dynamic lkFeedbackId;
  dynamic smileyId;
  bool? planStatusExceed;
  String? latestComment;
  String? whoCommented;
  String? date;

  Autogenerated({
    this.accountId,
    this.projectTaskId,
    this.projectId,
    this.taskType,
    this.phaseId,
    this.taskName,
    this.taskCategory,
    this.estStartDate,
    this.estEndDate,
    this.planStartDate,
    this.planEndDate,
    this.actStartDate,
    this.actEndDate,
    this.taskStatus,
    this.priorityId,
    this.sequence,
    this.assingedTo,
    this.collaboratorsId,
    this.estEfforts,
    this.dueDate,
    this.extEfforts,
    this.actEfforts,
    this.startTime,
    this.focus,
    this.invoiced,
    this.billable,
    this.snoozeTask,
    this.snoozeDate,
    this.editMode,
    this.createdBy,
    this.createdAt,
    this.updatedBy,
    this.updatedAt,
    this.attachment,
    this.taskDesc,
    this.refProjectTaskId,
    this.reportedDate,
    this.reportedTime,
    this.endTime,
    this.assingedName,
    this.createdName,
    this.collaborators,
    this.updatedName,
    this.myEfforts,
    this.allEfforts,
    this.taskDayAgo,
    this.projectName,
    this.priorityName,
    this.taskTypeName,
    this.taskCategoryName,
    this.focusId,
    this.taskStatusGroup,
    this.status,
    this.statusGroup,
    this.lkFeedbackId,
    this.smileyId,
    this.planStatusExceed,
    this.latestComment,
    this.whoCommented,
    this.date,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    accountId = json['account_id'];
    projectTaskId = json['project_task_id'];
    projectId = json['project_id'];
    taskType = json['task_type'];
    phaseId = getValue(json, 'phase_id');
    taskName = json['task_name'];
    taskCategory = json['task_category'];
    estStartDate = getValue(json, 'est_start_date');
    estEndDate = getValue(json, 'est_end_date');
    planStartDate = json['plan_start_date'];
    planEndDate = getValue(json, 'plan_end_date');
    actStartDate = json['act_start_date'];
    actEndDate = json['act_end_date'];
    taskStatus = json['task_status'];
    priorityId = json['priority_id'];
    sequence = getValue(json, 'sequence');
    assingedTo = json['assinged_to'];
    if (json['collaborators'] != null) {
      collaborators = <Collaborators>[];
      json['collaborators'].forEach((v) {
        collaborators!.add(new Collaborators.fromJson(v));
      });
    }
    collaboratorsId = getValue(json, 'collaborators_id');
    estEfforts = getValue(json, 'est_efforts');
    dueDate = getValue(json, 'due_date');
    extEfforts = getValue(json, 'ext_efforts');
    actEfforts = getValue(json, 'act_efforts');
    startTime = json['start_time'];
    focus = json['focus'];
    invoiced = json['invoiced'];
    billable = json['billable'];
    snoozeTask = getValue(json, 'snooze_task');
    snoozeDate = getValue(json, 'snooze_date');
    editMode = json['edit_mode'];
    createdBy = json['created_by'];
    createdAt = json['created_at'];
    updatedBy = json['updated_by'];
    updatedAt = json['updated_at'];
    attachment = getValue(json, 'attachment');
    taskDesc = getValue(json, 'task_desc');
    refProjectTaskId = getValue(json, 'ref_project_task_id');
    reportedDate = json['reported_date'];
    reportedTime = getValue(json, 'reported_time');
    endTime = getValue(json, 'end_time');
    assingedName = json['assinged_name'];
    createdName = json['created_name'];
    updatedName = json['updated_name'];
    myEfforts = json['my_efforts'];
    allEfforts = json['all_efforts'];
    taskDayAgo = json['task_day_ago'];
    projectName = json['project_name'];
    priorityName = json['priority_name'];
    taskTypeName = json['task_type_name'];
    taskCategoryName = json['task_category_name'];
    focusId = json['focus_id'];
    taskStatusGroup = json['task_status_group'];
    status = json['status'];
    statusGroup = json['status_group'];
    lkFeedbackId = getValue(json, 'lk_feedback_id');
    smileyId = getValue(json, 'smiley_id');
    planStatusExceed = json['plan_status_exceed'];
    latestComment = json['latest_comment'];
    whoCommented = json['who_commented'];
    date = json['date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['account_id'] = accountId;
    data['project_task_id'] = projectTaskId;
    data['project_id'] = projectId;
    data['task_type'] = taskType;
    data['phase_id'] = phaseId;
    data['task_name'] = taskName;
    data['task_category'] = taskCategory;
    data['est_start_date'] = estStartDate;
    data['est_end_date'] = estEndDate;
    data['plan_start_date'] = planStartDate;
    data['plan_end_date'] = planEndDate;
    data['act_start_date'] = actStartDate;
    data['act_end_date'] = actEndDate;
    data['task_status'] = taskStatus;
    data['priority_id'] = priorityId;
    data['sequence'] = sequence;
    data['assinged_to'] = assingedTo;
    data['collaborators_id'] = collaboratorsId;
    data['est_efforts'] = estEfforts;
    data['due_date'] = dueDate;
    data['ext_efforts'] = extEfforts;
    data['act_efforts'] = actEfforts;
    data['start_time'] = startTime;
    data['focus'] = focus;
    data['invoiced'] = invoiced;
    data['billable'] = billable;
    data['snooze_task'] = snoozeTask;
    if (this.collaborators != null) {
      data['collaborators'] =
          this.collaborators!.map((v) => v.toJson()).toList();
    }
    data['snooze_date'] = snoozeDate;
    data['edit_mode'] = editMode;
    data['created_by'] = createdBy;
    data['created_at'] = createdAt;
    data['updated_by'] = updatedBy;
    data['updated_at'] = updatedAt;
    data['attachment'] = attachment;
    data['task_desc'] = taskDesc;
    data['ref_project_task_id'] = refProjectTaskId;
    data['reported_date'] = reportedDate;
    data['reported_time'] = reportedTime;
    data['end_time'] = endTime;
    data['assinged_name'] = assingedName;
    data['created_name'] = createdName;
    data['updated_name'] = updatedName;
    data['my_efforts'] = myEfforts;
    data['all_efforts'] = allEfforts;
    data['task_day_ago'] = taskDayAgo;
    data['project_name'] = projectName;
    data['priority_name'] = priorityName;
    data['task_type_name'] = taskTypeName;
    data['task_category_name'] = taskCategoryName;
    data['focus_id'] = focusId;
    data['task_status_group'] = taskStatusGroup;
    data['status'] = status;
    data['status_group'] = statusGroup;
    data['lk_feedback_id'] = lkFeedbackId;
    data['smiley_id'] = smileyId;
    data['plan_status_exceed'] = planStatusExceed;
    data['latest_comment'] = latestComment;
    data['who_commented'] = whoCommented;
    data['date'] = date;
    return data;
  }

  dynamic getValue(Map<String, dynamic> json, String key) {
    if (json.containsKey(key)) {
      return json[key];
    } else {
      return null;
    }
  }
}

class Collaborators {
  int? assingedTo;
  String? assingedName;

  Collaborators({this.assingedTo, this.assingedName});

  Collaborators.fromJson(Map<String, dynamic> json) {
    assingedTo = json['assinged_to'];
    assingedName = json['assinged_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['assinged_to'] = this.assingedTo;
    data['assinged_name'] = this.assingedName;
    return data;
  }
}
