import 'dart:convert';
import 'dart:io';

import 'package:animated_emoji/emoji.dart';
import 'package:bms/Screens/AddTime.dart';
import 'package:bms/Screens/EditTask.dart';
import 'package:bms/pojos/models/CardPojodata.dart';
import 'package:bms/Screens/Comment.dart';
import 'package:bms/Screens/TimeSheet.dart';
import 'package:bms/Screens/addTaskPage.dart';
import 'package:bms/ApiCalls/apiCalls.dart';
import 'package:bms/pojos/models/PriorityDropdown.dart';
import 'package:bms/pojos/models/TaskStatusDropdown.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/cupertino.dart';
import "package:bms/pojos/models/TaskStatusDropdown.dart";
import "package:bms/pojos/models/PriorityDropdown.dart";
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_picker/image_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_rating_stars/flutter_rating_stars.dart';
import 'package:http/http.dart' as http;
import '../pojos/models/RatingCollaboratorpojo.dart';
import 'package:animated_emoji/animated_emoji.dart';
import 'package:flutter_rating_stars/flutter_rating_stars.dart';
import 'package:http/http.dart' as http;
import '../pojos/models/RatingCollaboratorpojo.dart';
import 'package:animated_emoji/animated_emoji.dart';

class myCards1 extends StatefulWidget {
  myCards1(
      {required this.Title,
      required this.taskTypeName,
      required this.description,
      required this.priority,
      required this.mydata,
      required this.colab,
      required this.plandate,
      required this.todate,
      required this.assigne,
      super.key,
      required this.projectid,
      required this.star,
      required this.emoji,
      required this.statusString,
      required this.priorityString,
      required this.index,
      required this.isFocused,
      required this.data,
      required this.refresh});

  final int index;
  final int projectid;
  int? star, emoji;

  final List<TaskStatusDropdown> mydata;
  final List<PrioritysDropdown> priority;
  final List<Collaborators> colab;
  final String Title,
      description,
      plandate,
      todate,
      assigne,
      taskTypeName,
      statusString,
      priorityString;
  final bool isFocused;
  Autogenerated data;
  Function refresh;
  @override
  State<myCards1> createState() => _myCards1State();
}

class _myCards1State extends State<myCards1> {
  getTimeState timer = getTimeState();
  var countReview = TextEditingController();
  List<String> attachment = [];
  TimeOfDay? mynew = TimeOfDay(hour: 12, minute: 00);
  TimeOfDay? mynew1 = TimeOfDay(hour: 12, minute: 00);
  var revise = TextEditingController();
  var comment = TextEditingController();
  DateTime todays = DateTime.now();
  bool isLoading = false;
  String Status = "Status";
  String priority = "Priority";
  int role_id = 0;
  DateTime selectedDate = DateTime.now();
  DateTime timesheetdate = DateTime.now();
  DateTime toselectedDate = DateTime.now();
  List<collaboratorsList> rating = [];
  List<String> colborators = [];
  bool isExternal = false;

  Color col = const Color.fromRGBO(255, 255, 231, 1);
  static String baseurl = "https://portalwiz.net/laravelapi/public/api/";
  // static String baseurl = "https://pw-bms-dev.portalwiz.in/laravelapi/public/api/";
  List<AnimatedEmojiData> emojidata = [
    AnimatedEmojis.angry,
    AnimatedEmojis.sad,
    AnimatedEmojis.slightlyHappy,
    AnimatedEmojis.blush,
    AnimatedEmojis.smile
  ];
  @override
  void initState() {
    setState(() {
      Status = widget.statusString;
      priority = widget.priorityString;
    });

    for (int i = 0; i < widget.colab.length; i++) {
      colborators.add(widget.colab[i].assingedName ?? "");
    }
    col = (widget.isFocused)
        ? Color.fromARGB(255, 192, 215, 255)
        : const Color.fromRGBO(255, 255, 231, 1);

    super.initState();
  }

  getrole() async {
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    setState(() {
      role_id = sharedPreferences.getInt("role_id") ?? 0;
    });
  }

  Future<void> _pickImageFromGallery(ImageSource imgsoruce) async {
    final ImagePicker _picker = ImagePicker();
    final XFile? pickedFile = await _picker.pickImage(source: imgsoruce);
    if (pickedFile != null) {
      setState(() {
        // Find the plan by planId and update its attachments

        attachment.add(pickedFile.path);
      });
    }
  }

  Future<void> _pickDocument() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles();
    if (result != null) {
      File file = File(result.files.single.path!);
      setState(() {
        attachment.add(file.path);
      });
    }
  }

  Future<void> fetchAssigneeCollaborators(int projectTaskId) async {
    final url = '${baseurl}fetch_assignee_collaborators';

    // Prepare the request body
    final body = {
      'project_task_id': "${projectTaskId}",
    };

    try {
      rating.clear();
      // Send POST request
      final response = await http.post(
        Uri.parse(url),
        body: body,
      );

      // Check if the request was successful
      if (response.statusCode == 200) {
        // Decode the response body
        final List<dynamic> data = jsonDecode(response.body);

        // Handle the response data
        for (var item in data) {
          rating.add(collaboratorsList.fromJson(item));
          // You can further process each item as needed
        }
      } else {
        // Handle the error
        print('Failed to load data. Status code: ${response.statusCode}');
      }
    } catch (e) {
      // Handle exceptions
      print('An error occurred: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      color: col,
      margin: EdgeInsets.all(MediaQuery.of(context).size.width * 0.03),
      child: Container(
        margin: EdgeInsets.all(MediaQuery.of(context).size.width * 0.02),
        width: MediaQuery.of(context).size.width,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(children: [
                  InkWell(
                    child: const Icon(
                      Icons.file_open_outlined,
                      size: 24,
                    ),
                    onTap: () {
                      //---------------
                    },
                  ),
                  SizedBox(
                    width: MediaQuery.of(context).size.width * 0.015,
                  ),
                  Container(
                    width: MediaQuery.of(context).size.width * 0.6,
                    child: Wrap(
                      children: [
                        Text(
                          widget.Title,
                          style: GoogleFonts.getFont(
                            'Lato',
                            fontWeight: FontWeight.w800,
                            fontSize: 12,
                            color: Colors.black,
                          ),
                          softWrap: true,
                          overflow: TextOverflow.visible,
                        ),
                      ],
                    ),
                  ),
                ]),
                Expanded(
                    child: Text(
                  " " + widget.taskTypeName,
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      background: Paint()..color = Colors.white,
                      color: Colors.pinkAccent,
                      fontWeight: FontWeight.w400,
                      fontSize: 10,
                    ),
                  ),
                  textAlign: TextAlign.end,
                  overflow: TextOverflow.fade,
                ))
              ],
            ),
            const SizedBox(
              height: 10,
            ),
            Row(children: [
              InkWell(
                child: const Icon(
                  Icons.message_outlined,
                  size: 25,
                ),
                onTap: () {
                  //-----------------------

                  // ApiCalls.getComments(dataOfCards[widget.index].accountId??1, dataOfCards[widget.index].projectId??0, dataOfCards[widget.index].projectTaskId??0);
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => CommentPage(
                                accid: dataOfCards[widget.index].accountId ?? 1,
                                projectId:
                                    dataOfCards[widget.index].projectId ?? 0,
                                projecttaskid:
                                    dataOfCards[widget.index].projectTaskId ??
                                        0,
                                created_by:
                                    dataOfCards[widget.index].createdBy ?? 0,
                                showProject: false,
                              )));
                },
              ),
              const SizedBox(
                width: 5,
              ),
              Expanded(
                child: Text(
                  widget.description,
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 14,
                    ),
                  ),
                  maxLines: null,
                  softWrap: true,
                  overflow: TextOverflow.visible,
                ),
              ),
              SizedBox(
                width: 5,
              ),
              Text(
                dataOfCards[widget.index].taskDayAgo ?? '0' + 'd',
                style: GoogleFonts.getFont(
                  'Lato',
                  textStyle: TextStyle(
                    color: Color.fromARGB(255, 32, 114, 255),
                    fontSize: 16,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              )
            ]),
            const SizedBox(
              height: 8,
            ),
            Row(
              children: [
                InkWell(
                  child: Icon(Icons.history),
                  onTap: () {
                    timeSheet.clear();
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => Timesheet(
                                  accid:
                                      dataOfCards[widget.index].accountId ?? 1,
                                  projecid:
                                      dataOfCards[widget.index].projectTaskId ??
                                          1,
                                  check: true,
                                )));
                  },
                ),
                SizedBox(
                  width: 8,
                ),
                Text(
                  'Est',
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      fontWeight: FontWeight.w500,
                      fontSize: 12,
                    ),
                  ),
                ),
                SizedBox(
                  width: 5,
                ),
                Text(
                  dataOfCards[widget.index].estEfforts ?? '00',
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      fontWeight: FontWeight.w700,
                      fontSize: 12,
                      color: Color.fromARGB(255, 33, 89, 243),
                    ),
                  ),
                ),
                SizedBox(
                  width: 15,
                ),
                Text(
                  'My',
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      fontWeight: FontWeight.w500,
                      fontSize: 12,
                    ),
                  ),
                ),
                SizedBox(
                  width: 5,
                ),
                Text(
                  dataOfCards[widget.index].myEfforts ?? '00',
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      fontWeight: FontWeight.w700,
                      fontSize: 12,
                      color: Color.fromARGB(255, 33, 89, 243),
                    ),
                  ),
                ),
                SizedBox(
                  width: 10,
                ),
                Text(
                  'All',
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      fontWeight: FontWeight.w500,
                      fontSize: 12,
                    ),
                  ),
                ),
                SizedBox(
                  width: 5,
                ),
                Text(
                  dataOfCards[widget.index].allEfforts ?? '0.00',
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      fontWeight: FontWeight.w700,
                      fontSize: 12,
                      color: Color.fromARGB(255, 33, 89, 243),
                    ),
                  ),
                )
              ],
            ),
            const SizedBox(
              height: 8,
            ),
            Row(children: [
              Padding(
                padding: EdgeInsets.fromLTRB(30, 5, 5, 10),
                child: Container(
                    height: MediaQuery.of(context).size.height * 0.03,
                    width: MediaQuery.of(context).size.width * 0.35,
                    decoration: BoxDecoration(
                        // borderRadius: BorderRadius.circular(24),
                        color: Colors.white),
                    child: DropdownButton(
                        underline: Text(""),
                        menuMaxHeight: 210,
                        isExpanded: true,
                        borderRadius: BorderRadius.circular(20),
                        hint: Padding(
                            padding: EdgeInsets.fromLTRB(10, 0, 0, 0),
                            child: Text(
                              Status,
                              style: GoogleFonts.getFont(
                                'Lato',
                                textStyle: TextStyle(
                                  fontSize: 12,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.black,
                                ),
                              ),
                            )),
                        items: widget.mydata
                            .map((item) => DropdownMenuItem(
                                value: item.taskStatus,
                                child: Text(
                                  item.taskStatus ?? "",
                                  style: GoogleFonts.getFont(
                                    'Lato',
                                    textStyle: TextStyle(
                                      fontSize: 15,
                                    ),
                                  ),
                                  overflow: TextOverflow.fade,
                                  maxLines: 2,
                                  softWrap: false,
                                )))
                            .toList(),
                        onChanged: (item) async {
                          setState(() {
                            Status = item.toString();
                            widget.data.status = item ?? "";
                            widget.data.taskStatus = widget.mydata
                                    .firstWhere((e) => e.taskStatus == item)
                                    .taskStatusId ??
                                widget.data.taskType;
                          });

                          await ApiCalls.updateProjectTaskByUser(widget.data);
                          widget.refresh();
                        })),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(30, 5, 5, 10),
                child: Container(
                    height: MediaQuery.of(context).size.height * 0.03,
                    width: MediaQuery.of(context).size.width * 0.35,
                    decoration: BoxDecoration(
                        // borderRadius: BorderRadius.circular(),
                        color: Colors.white),
                    child: DropdownButton(
                        underline: Text(""),
                        isExpanded: true,
                        borderRadius: BorderRadius.circular(20),
                        hint: Padding(
                            padding: EdgeInsets.fromLTRB(15, 0, 0, 0),
                            child: Text(
                              priority,
                              style: GoogleFonts.getFont(
                                'Lato',
                                textStyle: TextStyle(
                                  fontSize: 12,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.black,
                                ),
                              ),
                              textAlign: TextAlign.center,
                            )),
                        items: widget.priority
                            .map((item) => DropdownMenuItem(
                                value: item.priority,
                                child: Text(
                                  item.priority ?? "",
                                  style: GoogleFonts.getFont(
                                    'Lato',
                                    textStyle: TextStyle(
                                      fontSize: 15,
                                    ),
                                  ),
                                )))
                            .toList(),
                        onChanged: (item) async {
                          setState(() {
                            priority = item.toString();
                            widget.data.priorityId = widget.priority
                                    .firstWhere((e) => e.priority == item)
                                    .priorityId ??
                                widget.data.priorityId;
                          });

                          await ApiCalls.updateProjectTaskByUser(widget.data);
                        })),
              ),
            ]),
            Padding(
                padding: EdgeInsets.fromLTRB(30, 0, 0, 0),
                child: Row(children: [
                  Text(
                    'Plan',
                    style: GoogleFonts.getFont(
                      'Lato',
                      textStyle: TextStyle(
                        fontWeight: FontWeight.w600,
                        fontSize: 12,
                      ),
                    ),
                  ),
                  SizedBox(
                    width: 55,
                  ),
                  Text(
                    widget.plandate,
                    style: GoogleFonts.getFont(
                      'Lato',
                      textStyle: TextStyle(
                        fontWeight: FontWeight.w500,
                        fontSize: 12,
                      ),
                    ),
                  ),
                  SizedBox(
                    width: 40,
                  ),
                  Text(
                    'To',
                    style: GoogleFonts.getFont(
                      'Lato',
                      textStyle: TextStyle(
                        fontWeight: FontWeight.w600,
                        fontSize: 12,
                      ),
                    ),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  Text(
                    widget.todate,
                    style: GoogleFonts.getFont(
                      'Lato',
                      textStyle: TextStyle(
                        fontWeight: FontWeight.w500,
                        fontSize: 12,
                      ),
                    ),
                  )
                ])),
            const SizedBox(
              height: 8,
            ),
            Padding(
              padding: EdgeInsets.fromLTRB(30, 0, 0, 0),
              child: Row(children: [
                Text(
                  "Actual",
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      fontWeight: FontWeight.w600,
                      fontSize: 12,
                    ),
                  ),
                ),
                SizedBox(
                  width: 42,
                ),
                InkWell(
                  child: Text(
                    "${selectedDate.year}-${selectedDate.month}-${selectedDate.day}",
                    style: GoogleFonts.getFont(
                      'Lato',
                      textStyle: TextStyle(
                        fontWeight: FontWeight.w500,
                        fontSize: 12,
                        color: Color.fromARGB(255, 33, 89, 243),
                      ),
                    ),
                  ),
                  onTap: () async {
                    final DateTime? dateTime = await showDatePicker(
                      context: context,
                      firstDate: DateTime(1000),
                      lastDate: DateTime(3000),
                      initialDate: selectedDate,
                      barrierColor: Colors.transparent,
                      builder: (context, child) {
                        return Theme(
                          data: Theme.of(context).copyWith(
                            colorScheme: const ColorScheme.light(
                              primary:
                                  Colors.blueAccent, // header background color
                              onPrimary: Colors.black, // header text color
                              onSurface: Colors.black, // body text color
                            ),
                            textButtonTheme: TextButtonThemeData(
                              style: TextButton.styleFrom(
                                foregroundColor:
                                    Colors.blue, // button text color
                              ),
                            ),
                          ),
                          child: child!,
                        );
                      },
                    );

                    if (dateTime != null) {
                      setState(() {
                        selectedDate = dateTime;
                      });
                    }
                  },
                ),
                SizedBox(
                  width: 50,
                ),
                Text(
                  "To",
                  style: GoogleFonts.getFont(
                    'Lato',
                    textStyle: TextStyle(
                      fontWeight: FontWeight.w600,
                      fontSize: 12,
                    ),
                  ),
                ),
                SizedBox(
                  width: 20,
                ),
                InkWell(
                  child: Text(
                    "${toselectedDate.day}/${toselectedDate.month}/${toselectedDate.year}",
                    style: GoogleFonts.getFont(
                      'Lato',
                      textStyle: TextStyle(
                        fontWeight: FontWeight.w500,
                        fontSize: 12,
                        color: Color.fromARGB(255, 33, 89, 243),
                      ),
                    ),
                  ),
                  onTap: () async {
                    final DateTime? dateTime = await showDatePicker(
                        context: context,
                        firstDate: DateTime(1000),
                        lastDate: DateTime(3000),
                        initialDate: toselectedDate);
                    if (dateTime != null) {
                      setState(() {
                        toselectedDate = dateTime;
                      });
                    }
                  },
                )
              ]),
            ),
            Padding(
                padding: const EdgeInsets.fromLTRB(30, 5, 5, 5),
                child: Row(
                  children: [
                    Text(
                      "Assignee",
                      style: GoogleFonts.getFont(
                        'Lato',
                        textStyle: TextStyle(
                          fontSize: 12,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                    SizedBox(
                      width: MediaQuery.of(context).size.width * 0.08,
                    ),
                    InkWell(
                        onTap: () {
                          timeSheet.clear();
                          Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => Timesheet(
                                        accid: dataOfCards[widget.index]
                                                .accountId ??
                                            1,
                                        projecid: dataOfCards[widget.index]
                                                .projectTaskId ??
                                            1,
                                        check: false,
                                      )));
                        },
                        child: Text(
                          widget.assigne,
                          style: GoogleFonts.getFont(
                            'Lato',
                            textStyle: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w300,
                              color: Color.fromARGB(255, 3, 24, 255),
                            ),
                          ),
                        ))
                  ],
                )),
            Padding(
                padding: const EdgeInsets.fromLTRB(30, 0, 10, 10),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      "Collaborator",
                      style: GoogleFonts.getFont(
                        'Lato',
                        textStyle: TextStyle(
                          fontSize: 12,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                    SizedBox(
                      width: 10,
                    ),
                    Expanded(
                        child: Padding(
                            padding: EdgeInsets.fromLTRB(0, 3, 0, 0),
                            child: Text(
                              colborators.toString(),
                              style: GoogleFonts.getFont(
                                'Lato',
                                textStyle: TextStyle(
                                  fontSize: 11,
                                  fontWeight: FontWeight.w300,
                                ),
                              ),
                              softWrap: true,
                              maxLines: 3,
                              overflow: TextOverflow.fade,
                            )))
                  ],
                )),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      GestureDetector(
                          onTap: () {
                            getTimeSheetData();
                          },
                          child: Icon(
                            Icons.schedule_rounded,
                            size: 24,
                          )

                          // Text('Add Time',style: TextStyle(fontWeight: FontWeight.w600,color: Colors.blueAccent), // )

                          ),
                      SizedBox(
                        width: 20,
                      ),
                      (true)
                          ? PopupMenuButton<PopupMenu>(
                              surfaceTintColor: Colors.white,
                              icon: const Icon(
                                Icons.select_all,
                                size: 28,
                              ),
                              onSelected: (value) async {
                                if (value.name.toString() == "ProjectComment") {
                                  Navigator.push(
                                      context,
                                      MaterialPageRoute(
                                          builder: (context) => CommentPage(
                                                accid: dataOfCards[widget.index]
                                                        .accountId ??
                                                    1,
                                                projectId:
                                                    dataOfCards[widget.index]
                                                            .projectId ??
                                                        0,
                                                projecttaskid:
                                                    dataOfCards[widget.index]
                                                            .projectTaskId ??
                                                        0,
                                                created_by:
                                                    dataOfCards[widget.index]
                                                            .createdBy ??
                                                        0,
                                                showProject: true,
                                              )));
                                } else if (value.name.toString() == "Add") {
                                  Navigator.push(
                                      context,
                                      MaterialPageRoute(
                                          builder: (context) => AddTask(
                                                title: widget.Title,
                                                accid: dataOfCards[widget.index]
                                                        .accountId ??
                                                    1,
                                                projecid:
                                                    dataOfCards[widget.index]
                                                            .projectId ??
                                                        36,
                                              )));
                                } else if (value.name.toString() == "Edit") {
                                  Navigator.push(
                                      context,
                                      MaterialPageRoute(
                                          builder: (context) => EditTask(
                                                title: widget.Title,
                                                accid: dataOfCards[widget.index]
                                                        .accountId ??
                                                    0,
                                                projecid:
                                                    dataOfCards[widget.index]
                                                            .projectId ??
                                                        0,
                                                projecttaskid:
                                                    dataOfCards[widget.index]
                                                        .projectTaskId,
                                              )));
                                } else if (value.name.toString() == "Delete") {
                                  showDialog(
                                      context: context,
                                      builder: (context) {
                                        return AlertDialog(
                                          backgroundColor: Colors.white,
                                          title: const Text(
                                            "Are you Sure ?",
                                            style: TextStyle(
                                                fontSize: 22,
                                                fontWeight: FontWeight.w400),
                                          ),
                                          actions: [
                                            ElevatedButton(
                                                style: const ButtonStyle(
                                                    backgroundColor:
                                                        MaterialStatePropertyAll(
                                                            Colors.white)),
                                                onPressed: () {
                                                  Navigator.pop(context);
                                                },
                                                child: const Text(
                                                  "Cancel",
                                                  style: TextStyle(
                                                      fontSize: 14,
                                                      fontWeight:
                                                          FontWeight.w300,
                                                      color: Colors.black),
                                                )),
                                            ElevatedButton(
                                                style: const ButtonStyle(
                                                    backgroundColor:
                                                        MaterialStatePropertyAll(
                                                            Colors.redAccent)),
                                                onPressed: () async {
                                                  await ApiCalls.deleteTaskbyUser(
                                                      dataOfCards[widget.index]
                                                              .accountId ??
                                                          1,
                                                      dataOfCards[widget.index]
                                                              .projectTaskId ??
                                                          0,
                                                      context);
                                                },
                                                child: const Text(
                                                  "Delete",
                                                  style: TextStyle(
                                                      fontSize: 14,
                                                      fontWeight:
                                                          FontWeight.w300,
                                                      color: Colors.white),
                                                )),
                                          ],
                                        );
                                      });
                                }
                              },
                              itemBuilder: (context) => const [
                                    PopupMenuItem(
                                        value: PopupMenu.Add,
                                        child: Row(
                                            mainAxisAlignment:
                                                MainAxisAlignment.spaceBetween,
                                            children: [
                                              Text(
                                                "Add Another Task",
                                                style: TextStyle(fontSize: 12),
                                              ),
                                              Icon(Icons.add)
                                            ])),
                                    PopupMenuItem(
                                        value: PopupMenu.Edit,
                                        child: Row(
                                            mainAxisAlignment:
                                                MainAxisAlignment.spaceBetween,
                                            children: [
                                              Text(
                                                "Edit Task",
                                                style: TextStyle(fontSize: 12),
                                              ),
                                              Icon(Icons.add)
                                            ])),
                                    PopupMenuItem(
                                        value: PopupMenu.Delete,
                                        child: Row(
                                            mainAxisAlignment:
                                                MainAxisAlignment.spaceBetween,
                                            children: [
                                              Text(
                                                "Delete Task",
                                                style: TextStyle(fontSize: 12),
                                              ),
                                              Icon(Icons.delete_outline)
                                            ])),
                                    PopupMenuItem(
                                        value: PopupMenu.ProjectComment,
                                        child: Row(
                                            mainAxisAlignment:
                                                MainAxisAlignment.spaceBetween,
                                            children: [
                                              Text(
                                                "Project Comment",
                                                style: TextStyle(fontSize: 12),
                                              ),
                                              Icon(Icons.comment_bank_outlined)
                                            ])),
                                  ])
                          : Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                  GestureDetector(
                                      onTap: () {
                                        Navigator.push(
                                            context,
                                            MaterialPageRoute(
                                                builder: (context) =>
                                                    CommentPage(
                                                      accid: dataOfCards[
                                                                  widget.index]
                                                              .accountId ??
                                                          1,
                                                      projectId: dataOfCards[
                                                                  widget.index]
                                                              .projectId ??
                                                          0,
                                                      projecttaskid: dataOfCards[
                                                                  widget.index]
                                                              .projectTaskId ??
                                                          0,
                                                      created_by: dataOfCards[
                                                                  widget.index]
                                                              .createdBy ??
                                                          0,
                                                      showProject: true,
                                                    )));
                                      },
                                      child: Icon(Icons.comment_bank_outlined))
                                ]),
                    ]),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    GestureDetector(
                      onTap: () async {
                        await fetchAssigneeCollaborators(widget.projectid);
                        showDialog(
                            context: context,
                            builder: (context) {
                              return ListView.builder(
                                  itemCount: rating.length,
                                  itemBuilder: (context, index) {
                                    return CollaboratorsCard(
                                      collaborator: rating[index],
                                      callback: () async {
                                        await fetchAssigneeCollaborators(
                                            widget.projectid);
                                      },
                                    );
                                  });
                            });
                      },
                      child: RatingStars(
                        axis: Axis.horizontal,
                        value:
                            (widget.star == null ? 0 : widget.star!).toDouble(),
                        starCount: 5,
                        starSize: 18,
                        valueLabelColor: const Color(0xff9b9b9b),
                        valueLabelRadius: 10,
                        maxValue: 5,
                        starSpacing: 2,
                        maxValueVisibility: true,
                        valueLabelVisibility: false,
                        animationDuration: Duration(milliseconds: 1000),
                        valueLabelPadding: const EdgeInsets.symmetric(
                            vertical: 1, horizontal: 8),
                        valueLabelMargin: const EdgeInsets.only(right: 8),
                        starOffColor: const Color(0xffe7e8ea),
                        starColor: Colors.yellow,
                        angle: 0,
                      ),
                    ),
                    SizedBox(
                      width: 15,
                    ),
                    Visibility(
                        visible: !(widget.emoji == null),
                        child: AnimatedEmoji(
                          emojidata[(widget.emoji ?? 1) - 1],
                          size: 28,
                        )),
                  ],
                ),
              ],
            ),
            Container(
              padding: EdgeInsets.symmetric(horizontal: 10),
              height: attachment != null && attachment.isNotEmpty ? 100 : 0,
              child: ListView.builder(
                scrollDirection: Axis.horizontal,
                itemCount: attachment.length ?? 0,
                itemBuilder: (context, attIndex) {
                  if (!(attachment[attIndex].contains(".pdf")) &&
                      !(attachment[attIndex].contains("http"))) {
                    return Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Stack(
                        children: [
                          GestureDetector(
                            onTap: () => showDialog(
                                context: (context),
                                builder: (context) {
                                  return Center(
                                    child: Container(
                                      child: Stack(
                                        alignment: Alignment.topRight,
                                        children: [
                                          Image.file(
                                            File(attachment[attIndex]),
                                            fit: BoxFit.cover,
                                          ),
                                          IconButton(
                                            icon: Icon(Icons.cancel,
                                                color: Colors.red),
                                            onPressed: () {
                                              Navigator.pop(context);
                                            },
                                          ),
                                        ],
                                      ),
                                    ),
                                  );
                                }),
                            child: Image.file(
                              File(attachment[attIndex]),
                              width: 100,
                              height: 100,
                              fit: BoxFit.cover,
                            ),
                          ),
                          Positioned(
                            right: 0,
                            child: IconButton(
                              icon:
                                  Icon(Icons.remove_circle, color: Colors.red),
                              onPressed: () {
                                setState(() {
                                  attachment.removeAt(attIndex);
                                });
                              },
                            ),
                          ),
                        ],
                      ),
                    );
                  } else if ((attachment[attIndex].contains("https://"))) {
                    return GestureDetector(
                      onTap: () async {},
                      child: Container(
                        margin: EdgeInsets.symmetric(horizontal: 10),
                        child: Icon(
                          Icons.link,
                          color: Colors.blueAccent,
                          size: 46,
                        ),
                      ),
                    );
                  } else {
                    return GestureDetector(
                      onTap: () async {
                        print("https://docs.google.com/gview/" +
                            attachment[attIndex]);
                      },
                      child: Container(
                        margin: EdgeInsets.symmetric(horizontal: 10),
                        child: Icon(
                          Icons.picture_as_pdf_outlined,
                          color: Colors.redAccent,
                          size: 46,
                        ),
                      ),
                    );
                  }
                },
              ),
            ),
            Padding(
              padding:
                  const EdgeInsets.symmetric(horizontal: 10.0, vertical: 5),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  GestureDetector(
                    onTap: () {
                      _pickImageFromGallery(ImageSource.camera);
                    },
                    child: Container(
                      width: 80,
                      color: Colors.grey.shade200,
                      child: Icon(Icons.add_a_photo_outlined,
                          color: Colors.blueAccent),
                    ),
                  ),
                  GestureDetector(
                    onTap: () {
                      _pickDocument();
                    },
                    child: Container(
                      width: 80,
                      color: Colors.grey.shade200,
                      child:
                          Icon(Icons.edit_document, color: Colors.blueAccent),
                    ),
                  ),
                  GestureDetector(
                    onTap: () {
                      _pickImageFromGallery(ImageSource.gallery);
                    },
                    child: Container(
                      width: 80,
                      color: Colors.grey.shade200,
                      child: Icon(Icons.photo, color: Colors.blueAccent),
                    ),
                  ),
                  GestureDetector(
                    onTap: () {
                      TextEditingController linkadd = TextEditingController();
                      showDialog(
                          context: context,
                          builder: (context) {
                            return Dialog(
                              child: Card(
                                child: Container(
                                  height: 160,
                                  color: Colors.transparent,
                                  child: Column(
                                    children: [
                                      Padding(
                                        padding: EdgeInsets.symmetric(
                                            horizontal: 10, vertical: 10),
                                        child: Text(
                                          "Add Link",
                                          style: TextStyle(fontSize: 16),
                                        ),
                                      ),
                                      Padding(
                                        padding: const EdgeInsets.symmetric(
                                            horizontal: 10.0, vertical: 6),
                                        child: TextField(
                                          controller: linkadd,
                                          decoration: InputDecoration(
                                              contentPadding:
                                                  EdgeInsets.only(left: 5),
                                              border: OutlineInputBorder(
                                                  borderRadius:
                                                      BorderRadius.circular(
                                                          11))),
                                        ),
                                      ),
                                      ElevatedButton(
                                          onPressed: () {
                                            setState(() {
                                              (attachment).add(linkadd.text);
                                            });

                                            linkadd.clear();
                                            Navigator.pop(context);
                                          },
                                          child: Text("Add")),
                                    ],
                                  ),
                                ),
                              ),
                            );
                          });
                    },
                    child: Container(
                      width: 80,
                      color: Colors.grey.shade200,
                      child: Icon(Icons.link, color: Colors.blueAccent),
                    ),
                  ),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }

  void getTimeSheetData() {
    showDialog(
      context: context,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setState) {
            return Dialog(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              child: SingleChildScrollView(
                child: Container(
                  width: MediaQuery.of(context).size.width * 0.9,
                  padding: EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Row(
                        children: [
                          Icon(Icons.calendar_month, size: 16),
                          SizedBox(width: 4),
                          Text(
                            "${timesheetdate.year}-${timesheetdate.month}-${timesheetdate.day}",
                            style: TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                              color: Colors.grey.shade600,
                            ),
                          ),
                        ],
                      ),
                      SizedBox(height: 16),
                      Text(
                        widget.description,
                        style: GoogleFonts.getFont(
                          'Lato',
                          textStyle: TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 16,
                          ),
                        ),
                      ),
                      SizedBox(height: 16),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text("Start", style: TextStyle(fontSize: 14)),
                              GetTime(
                                getselected: (p0) {
                                  setState(() {
                                    mynew = p0;
                                  });
                                },
                              ),
                            ],
                          ),
                          Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text("End", style: TextStyle(fontSize: 14)),
                              GetTime(
                                getselected: (p0) {
                                  setState(() {
                                    mynew1 = p0;
                                  });
                                },
                              ),
                            ],
                          ),
                          Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text("Total Hrs:",
                                  style: TextStyle(fontSize: 14)),
                              SizedBox(width: 5),
                              Text("8"),
                            ],
                          ),
                        ],
                      ),
                      SizedBox(height: 16),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              Text("Rev:", style: TextStyle(fontSize: 14)),
                              IconButton(
                                icon: Icon(Icons.remove, size: 16),
                                onPressed: () {
                                  int value = int.tryParse(revise.text) ?? 0;
                                  setState(() {
                                    if (value > 0) value--;
                                    revise.text = value.toString();
                                  });
                                },
                              ),
                              Container(
                                width: 40,
                                child: TextField(
                                  controller: revise,
                                  keyboardType: TextInputType.number,
                                  textAlign: TextAlign.center,
                                  decoration: InputDecoration(
                                    contentPadding: EdgeInsets.zero,
                                    isDense: true,
                                    border: OutlineInputBorder(),
                                  ),
                                ),
                              ),
                              IconButton(
                                icon: Icon(Icons.add, size: 16),
                                onPressed: () {
                                  int value = int.tryParse(revise.text) ?? 0;
                                  setState(() {
                                    value++;
                                    revise.text = value.toString();
                                  });
                                },
                              ),
                            ],
                          ),
                          Row(
                            children: [
                              Text("Ex:", style: TextStyle(fontSize: 14)),
                              Switch(
                                value: isExternal,
                                onChanged: (bool value) {
                                  setState(() {
                                    isExternal = value;
                                  });
                                },
                              ),
                            ],
                          ),
                        ],
                      ),
                      SizedBox(height: 16),
                      TextFormField(
                        decoration: InputDecoration(
                          labelText: "Comment",
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                        controller: comment,
                        minLines: 2,
                        maxLines: null,
                        keyboardType: TextInputType.multiline,
                        validator: (value) {
                          if (value == null || value.isEmpty) {
                            return 'Comment is required';
                          }
                          return null;
                        },
                      ),
                      SizedBox(height: 16),
                      Align(
                        alignment: Alignment.bottomRight,
                        child: Container(
                          width: MediaQuery.of(context).size.width * 0.4,
                          height: MediaQuery.of(context).size.height * 0.04,
                          child: isLoading
                              ? Center(child: CircularProgressIndicator())
                              : ElevatedButton(
                                  onPressed: () async {
                                    if (comment.text.isEmpty) {
                                      ScaffoldMessenger.of(context)
                                          .showSnackBar(
                                        SnackBar(
                                          content: Text('Comment is required'),
                                        ),
                                      );
                                      return;
                                    }

                                    setState(() {
                                      isLoading = true;
                                    });
                                    bool response =
                                        await ApiCalls.addTimeSheetOfProject(
                                      dataOfCards[widget.index].projectTaskId ??
                                          0,
                                      dataOfCards[widget.index].accountId ?? 0,
                                      dataOfCards[widget.index].projectId ?? 0,
                                      dataOfCards[widget.index].actStartDate ??
                                          "00/00/0000",
                                      dataOfCards[widget.index].actEndDate ??
                                          "00/00/0000",
                                      dataOfCards[widget.index].taskStatus ?? 0,
                                      dataOfCards[widget.index].priorityId ?? 0,
                                      dataOfCards[widget.index].assingedTo ?? 0,
                                      dataOfCards[widget.index].createdBy ?? 0,
                                      dataOfCards[widget.index].taskDesc ?? "",
                                      "${timesheetdate.year}/${timesheetdate.month}/${timesheetdate.day}",
                                      comment.text.toString(),
                                      mynew!.format(context),
                                      mynew1!.format(context),
                                    );
                                    setState(() {
                                      isLoading = !response;
                                    });
                                    revise.clear();
                                    comment.clear();

                                    if (response) {
                                      setState(() {
                                        isLoading = false;
                                      });

                                      Navigator.pop(context);
                                      ScaffoldMessenger.of(context)
                                          .showSnackBar(
                                        SnackBar(
                                          content: Text(
                                            "Time Sheet Updated",
                                            style: TextStyle(
                                              color: Colors.white,
                                            ),
                                          ),
                                          backgroundColor: Colors.transparent,
                                        ),
                                      );
                                    }
                                  },
                                  child: Text("Submit"),
                                ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        );
      },
    );
  }
}

enum PopupMenu { Add, Edit, Delete, ProjectComment }

// class CollaboratorsCard extends StatefulWidget {
//   final collaboratorsList collaborator;
//   Function callback;

//   CollaboratorsCard({required this.collaborator, required this.callback});

//   @override
//   _CollaboratorsCardState createState() => _CollaboratorsCardState();
// }

// class _CollaboratorsCardState extends State<CollaboratorsCard> {
//   TextEditingController _commentController = TextEditingController();
//   bool _isEmojisVisible = false;
//   int? _selectedEmoji;
//   double starValue = 0;
//   AnimatedEmojiData? animatedEmojiData;

//   void _toggleEmojis() {
//     setState(() {
//       _isEmojisVisible = !_isEmojisVisible;
//     });
//   }

//   void _submitComment() async {
//     // Handle comment submission
//     SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
//     await ApiCalls.addProjectTasksByUser(
//         accountId: sharedPreferences.getInt("account_id") ?? 0,
//         roleId: sharedPreferences.getInt("role_id") ?? 0,
//         userId: sharedPreferences.getInt("user_id") ?? 0,
//         projectTaskId: widget.collaborator.projectTaskId ?? 0,
//         assigneeId: widget.collaborator.assigneeId,
//         lkFeedbackId: starValue.round(),
//         smileyId: _selectedEmoji ?? 0,
//         comment: _commentController.text);
//     //print({"accountId":sharedPreferences.getInt("account_id")??0, 'roleId': sharedPreferences.getInt("role_id")??0, 'userId': sharedPreferences.getInt("user_id")??0, "projectTaskId": widget.collaborator.projectTaskId??0, "assigneeId":widget.collaborator.assigneeId , "lkFeedbackId": starValue.round(), "smileyId": _selectedEmoji??0, "comment": _commentController.text});
//     print('Comment submitted: ${_commentController.text}');
//     widget.callback();
//     _commentController.clear();
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Card(
//       elevation: 6,
//       margin: EdgeInsets.all(10),
//       color: Colors.grey[200],
//       shape: RoundedRectangleBorder(
//         borderRadius: BorderRadius.circular(12),
//       ),
//       child: Padding(
//         padding: const EdgeInsets.all(16.0),
//         child: Column(
//           crossAxisAlignment: CrossAxisAlignment.start,
//           children: [
//             Row(
//               mainAxisAlignment: MainAxisAlignment.spaceBetween,
//               children: [
//                 Expanded(
//                   child: Text(
//                     widget.collaborator.name ?? '',
//                     style: TextStyle(
//                         fontWeight: FontWeight.bold,
//                         fontSize: 16,
//                         color: Colors.black87),
//                   ),
//                 ),
//                 SizedBox(width: 8),
//                 Text(
//                   widget.collaborator.displayName ?? '',
//                   style: TextStyle(fontSize: 14, color: Colors.black54),
//                 ),
//               ],
//             ),
//             SizedBox(height: 5),
//             Row(
//               children: [
//                 Expanded(
//                   child: RatingStars(
//                     axis: Axis.horizontal,
//                     value: starValue,
//                     onValueChanged: (v) {
//                       setState(() {
//                         starValue = v;
//                       });
//                     },
//                     starCount: 5,
//                     starSize: 24,
//                     valueLabelColor: const Color(0xff9b9b9b),
//                     valueLabelRadius: 10,
//                     maxValue: 5,
//                     starSpacing: 2,
//                     maxValueVisibility: true,
//                     valueLabelVisibility: false,
//                     animationDuration: Duration(milliseconds: 1000),
//                     valueLabelPadding:
//                         const EdgeInsets.symmetric(vertical: 1, horizontal: 8),
//                     valueLabelMargin: const EdgeInsets.only(right: 8),
//                     starOffColor: const Color(0xffe7e8ea),
//                     starColor: Colors.yellow,
//                     angle: 12,
//                   ),
//                 ),
//                 IconButton(
//                   icon: AnimatedEmoji(
//                     _selectedEmoji != null
//                         ? animatedEmojiData ?? AnimatedEmojis.slightlyHappy
//                         : AnimatedEmojis.slightlyHappy,
//                     size: 30,
//                   ),
//                   onPressed: _toggleEmojis,
//                 ),
//               ],
//             ),
//             if (_isEmojisVisible)
//               Row(
//                 mainAxisAlignment: MainAxisAlignment.center,
//                 children: [
//                   IconButton(
//                     icon: AnimatedEmoji(AnimatedEmojis.angry, size: 24),
//                     onPressed: () => setState(() {
//                       _selectedEmoji = 0;
//                       animatedEmojiData = AnimatedEmojis.angry;
//                     }),
//                   ),
//                   IconButton(
//                     icon: AnimatedEmoji(AnimatedEmojis.sad, size: 24),
//                     onPressed: () => setState(() {
//                       _selectedEmoji = 1;
//                       animatedEmojiData = AnimatedEmojis.sad;
//                     }),
//                   ),
//                   IconButton(
//                     icon: AnimatedEmoji(AnimatedEmojis.slightlyHappy, size: 24),
//                     onPressed: () => setState(() {
//                       _selectedEmoji = 2;
//                       animatedEmojiData = AnimatedEmojis.slightlyHappy;
//                     }),
//                   ),
//                   IconButton(
//                     icon: AnimatedEmoji(AnimatedEmojis.smile, size: 24),
//                     onPressed: () => setState(() {
//                       _selectedEmoji = 3;
//                       animatedEmojiData = AnimatedEmojis.smile;
//                     }),
//                   ),
//                 ],
//               ),
//             SizedBox(height: 5),
//             TextField(
//               controller: _commentController,
//               decoration: InputDecoration(
//                 contentPadding: EdgeInsets.only(left: 5),
//                 border:
//                     OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
//                 hintText: 'Enter your comment',
//                 filled: true,
//                 fillColor: Colors.white,
//               ),
//               maxLines: 2,
//             ),
//             SizedBox(height: 5),
//             Center(
//               child: ElevatedButton(
//                 onPressed: _submitComment,
//                 child: Text('Submit'),
//                 style: ElevatedButton.styleFrom(
//                   shape: RoundedRectangleBorder(
//                     borderRadius: BorderRadius.circular(8),
//                   ),
//                 ),
//               ),
//             ),
//           ],
//         ),
//       ),
//     );
//   }
// }

class CollaboratorsCard extends StatefulWidget {
  final collaboratorsList collaborator;
  Function callback;

  CollaboratorsCard({required this.collaborator, required this.callback});

  @override
  _CollaboratorsCardState createState() => _CollaboratorsCardState();
}

class _CollaboratorsCardState extends State<CollaboratorsCard> {
  TextEditingController _commentController = TextEditingController();
  bool _isEmojisVisible = false;
  int? _selectedEmoji;
  double starValue = 0;
  AnimatedEmojiData? animatedEmojiData;

  @override
  void initState() {
    setDataofCards();
    // TODO: implement initState
    super.initState();
  }

  void setDataofCards() async {
    setState(() {
      _commentController.text = widget.collaborator.comment ?? "";
      _selectedEmoji = widget.collaborator.smileyId ?? 0;
      starValue = double.parse("${widget.collaborator.lkFeedbackId ?? 0}");
      animatedEmojiData;
    });
  }

  void _toggleEmojis() {
    setState(() {
      _isEmojisVisible = !_isEmojisVisible;
    });
  }

  void _submitComment() async {
    // Handle comment submission
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    await ApiCalls.addProjectTasksByUser(
        accountId: sharedPreferences.getInt("account_id") ?? 0,
        roleId: sharedPreferences.getInt("role_id") ?? 0,
        userId: sharedPreferences.getInt("user_id") ?? 0,
        projectTaskId: widget.collaborator.projectTaskId ?? 0,
        assigneeId: widget.collaborator.assigneeId,
        lkFeedbackId: starValue.round(),
        smileyId: _selectedEmoji ?? 0,
        comment: _commentController.text);
    //print({"accountId":sharedPreferences.getInt("account_id")??0, 'roleId': sharedPreferences.getInt("role_id")??0, 'userId': sharedPreferences.getInt("user_id")??0, "projectTaskId": widget.collaborator.projectTaskId??0, "assigneeId":widget.collaborator.assigneeId , "lkFeedbackId": starValue.round(), "smileyId": _selectedEmoji??0, "comment": _commentController.text});
    print('Comment submitted: ${_commentController.text}');
    Fluttertoast.showToast(
        msg: 'Comment submitted: ${_commentController.text}');
    widget.callback();
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 6,
      margin: EdgeInsets.all(10),
      color: Colors.grey[200],
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                SizedBox(width: 8),
                Expanded(
                  child: Text(
                    widget.collaborator.displayName ?? '',
                    style: TextStyle(fontSize: 16, color: Colors.black54),
                  ),
                ),
              ],
            ),
            SizedBox(height: 5),
            Row(
              children: [
                Expanded(
                  child: RatingStars(
                    axis: Axis.horizontal,
                    value: starValue,
                    onValueChanged: (v) {
                      setState(() {
                        starValue = v;
                      });
                    },
                    starCount: 5,
                    starSize: 24,
                    valueLabelColor: Color.fromARGB(255, 115, 114, 114),
                    valueLabelRadius: 10,
                    maxValue: 5,
                    starSpacing: 2,
                    maxValueVisibility: true,
                    valueLabelVisibility: false,
                    animationDuration: Duration(milliseconds: 1000),
                    valueLabelPadding:
                        const EdgeInsets.symmetric(vertical: 1, horizontal: 8),
                    valueLabelMargin: const EdgeInsets.only(right: 8),
                    starOffColor: const Color(0xffe7e8ea),
                    starColor: Colors.yellow,
                    angle: 0,
                  ),
                ),
                IconButton(
                  icon: AnimatedEmoji(
                    _selectedEmoji != null
                        ? animatedEmojiData ?? AnimatedEmojis.slightlyHappy
                        : AnimatedEmojis.slightlyHappy,
                    size: 30,
                  ),
                  onPressed: _toggleEmojis,
                ),
              ],
            ),
            if (_isEmojisVisible)
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  IconButton(
                    icon: AnimatedEmoji(AnimatedEmojis.angry, size: 24),
                    onPressed: () => setState(() {
                      _selectedEmoji = 1;
                      animatedEmojiData = AnimatedEmojis.angry;
                    }),
                  ),
                  IconButton(
                    icon: AnimatedEmoji(AnimatedEmojis.sad, size: 24),
                    onPressed: () => setState(() {
                      _selectedEmoji = 2;
                      animatedEmojiData = AnimatedEmojis.sad;
                    }),
                  ),
                  IconButton(
                    icon: AnimatedEmoji(AnimatedEmojis.slightlyHappy, size: 24),
                    onPressed: () => setState(() {
                      _selectedEmoji = 3;
                      animatedEmojiData = AnimatedEmojis.slightlyHappy;
                    }),
                  ),
                  IconButton(
                    icon: AnimatedEmoji(AnimatedEmojis.blush, size: 24),
                    onPressed: () => setState(() {
                      _selectedEmoji = 4;
                      animatedEmojiData = AnimatedEmojis.blush;
                    }),
                  ),
                  IconButton(
                    icon: AnimatedEmoji(AnimatedEmojis.smile, size: 24),
                    onPressed: () => setState(() {
                      _selectedEmoji = 5;
                      animatedEmojiData = AnimatedEmojis.smile;
                    }),
                  ),
                ],
              ),
            Text(
              widget.collaborator.name ?? '',
              style: TextStyle(fontSize: 14, color: Colors.black87),
            ),
            SizedBox(height: 5),
            TextField(
              controller: _commentController,
              decoration: InputDecoration(
                contentPadding: EdgeInsets.only(left: 5),
                border:
                    OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                hintText: 'Enter your comment',
                filled: true,
                fillColor: Colors.white,
              ),
              maxLines: 2,
            ),
            SizedBox(height: 5),
            Center(
              child: ElevatedButton(
                onPressed: _submitComment,
                child: Text('Submit'),
                style: ElevatedButton.styleFrom(
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
