import 'package:bms/Screens/LeaveTracker.dart';
import 'package:bms/pojos/models/CardPojodata.dart';
import 'package:bms/pojos/models/CategorysDropdown.dart';
import 'package:bms/pojos/models/CollaboratorsDropdown.dart';
import 'package:bms/pojos/models/Commentpojo.dart';
import 'package:bms/pojos/models/ContactModels.dart';
import 'package:bms/pojos/models/Enquirepojo.dart';
import 'package:bms/pojos/models/FilterDataPojo.dart';
import 'package:bms/pojos/models/PriorityDropdown.dart';
import 'package:bms/pojos/models/TaskDropdown.dart';
import 'package:bms/pojos/models/TaskStatusDropdown.dart';

import 'package:bms/pojos/models/TimesheetPojo.dart';
import 'package:bms/pojos/models/enquireComment.dart';
import 'package:bms/pojos/models/getAllDataofEnquireCard.dart';
import 'package:bms/pojos/models/snoozedPojo.dart';
import 'package:bms/widgets/enquireCommentCard.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:get/get.dart';
import 'package:multi_dropdown/models/value_item.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

List<Autogenerated> dataOfCards = <Autogenerated>[];
List<Autogenerated> dataofCardClear = [];
List<TaskStatusDropdown> myStatus = [];
List<Taskdropdown> getTasks = [];
List<CategorysDropdown> myCategories = [];
List<PrioritysDropdown> myprority = [];
List<Commentpojo> myComment = [];
List<CollaboratorsDropdown> collboraotrs = [];
List<TimeSheetPojo> timeSheet = [];

class ApiCalls {
  // static String baseurl =
  //     "https://pw-bms-dev.portalwiz.in/laravelapi/public/api/";
  static String baseurl = "https://portalwiz.net/laravelapi/public/api/";
  static Future<dynamic> getDataofCards(
      String statusId,
      List<int> createby,
      List<int> tasktype,
      List<int> taskcategory,
      List<int>? projectype,
      List<int>? projectid,
      List<int>? assignee,
      List<int>? taskstatus) async {
    dataOfCards.clear();
    var pref = await SharedPreferences.getInstance();

    try {
      Uri uri = Uri.parse('${baseurl}fetch_project_tasks_by_user');

      var body = {
        "account_id": pref.getInt('account_id').toString(),
        "user_id": pref.getInt('user_id').toString(),
        "role_id": pref.getInt('role_id').toString(),
        "assinged_to": assignee.isNull ? null : assignee,
        "status_group_id": statusId,
        "project_id": projectid.isNull ? null : projectid,
        "project_type_id": projectype.isNull ? null : projectype,
        "task_status_id": taskstatus.isNull ? null : taskstatus,
        "task_type_id": tasktype.isEmpty
            ? null
            : tasktype, // Assuming the passed 'data' corresponds to 'task_type_id'
        "task_category": taskcategory.isEmpty ? null : taskcategory,
        "created_by": createby.isEmpty ? null : createby,
      };
      print(body);

      var response = await http.post(uri,
          body: jsonEncode(body),
          headers: {"Content-Type": "application/json"});

      var responseData = jsonDecode(response.body);

      for (Map<String, dynamic> i in responseData) {
        dataOfCards.add(Autogenerated.fromJson(i));
      }
    } catch (e) {
      print(e);
    }
  }

  static Future<dynamic> getStatus(int accid) async {
    var body2 = {
      "account_id": "${accid}",
    };

    Uri uri2 = Uri.parse('${baseurl}fetch_task_status?');
    Uri uripriority = Uri.parse('${baseurl}fetch_priority');
    try {
      var response2 = await http.post(uri2, body: body2);
      var status = jsonDecode(response2.body.toString());
      var responsepriority = await http.get(uripriority);
      var priority = jsonDecode(responsepriority.body.toString());

      myStatus.clear();
      for (Map<String, dynamic> i in status) {
        myStatus.add(TaskStatusDropdown.fromJson(i));
      }
      myprority.clear();
      for (Map<String, dynamic> i in priority) {
        myprority.add(PrioritysDropdown.fromJson(i));
      }
    } catch (E) {
      print(E);
    }
  }

  static Future<void> getComments(
      int accid, int projectid, int projectTaskId) async {
    var body = {
      "account_id": accid.toString(),
      "project_id": projectid.toString(),
      "project_task_id": projectTaskId.toString()
    };
    try {
      Uri url = Uri.parse("${baseurl}fetch_task_comment?");

      final response = await http.post(url, body: body);

      if (response.statusCode == 200) {
        myComment.clear();
        for (Map<String, dynamic> i in jsonDecode(response.body.toString())) {
          myComment.add(Commentpojo.fromJson(i));
        }
      }
    } catch (e) {
      print(e);
    }
  }

//----------------------------------------------------
  static Future<void> getProjectComment(int accid, int projectid) async {
    var body = {
      "account_id": accid.toString(),
      "project_id": projectid.toString(),
    };

    Uri url = Uri.parse("${baseurl}fetch_project_comment?");
    try {
      final response = await http.post(url, body: body);

      if (response.statusCode == 200) {
        myComment.clear();
        for (Map<String, dynamic> i in jsonDecode(response.body.toString())) {
          myComment.add(Commentpojo.fromJson(i));
        }
      }
    } catch (e) {
      print(e);
    }
  }

  static Future<bool> postComment(int accid, int projectid, int projectTaskId,
      int createby, String message, int useid) async {
    var body = {
      "account_id": accid.toString(),
      "project_id": projectid.toString(),
      "project_task_id": projectTaskId.toString(),
      "created_by": createby.toString(),
      "message": message,
      "user_id": useid.toString(),
    };

    Uri url = Uri.parse("${baseurl}add_task_comment?");

    final response = await http.post(url, body: body);

    if (response.statusCode == 200) {
      return true;
    } else {
      return false;
    }
  }

  static Future<dynamic> getDataofTimeShaeet(int accid, int userid) async {
    var body = {
      "account_id": accid.toString(),
      "user_id": userid.toString(),
    };

// var body={
//     "account_id": "1100",
//     "user_id": 97.toString()
// };

    Uri url = Uri.parse("${baseurl}fetch_timesheet_by_user?");

    final response = await http.post(url, body: body);

    if (response.statusCode == 200) {
      timeSheet.clear();
      for (Map<String, dynamic> i in jsonDecode(response.body.toString())) {
        timeSheet.add(TimeSheetPojo.fromJson(i));
      }
    }
  }

  static Future<dynamic> deleteTaskbyUser(
      int accid, int projectid, BuildContext context) async {
    var body = {
      "account_id": accid.toString(),
      "project_id": projectid.toString(),
    };

    Uri url = Uri.parse("${baseurl}delete_project_task?");

    final response = await http.post(url, body: body);

    if (response.statusCode == 200) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          backgroundColor: Colors.redAccent,
          content: Text(jsonDecode(response.body.toString())['message'])));
    }
  }

  static Future<dynamic> gettaskByUser(int accid) async {
    Uri url = Uri.parse("${baseurl}fetch_task_types?");

    final response = await http.get(url);
    print(response.body);

    if (response.statusCode == 200) {
      getTasks.clear();

      for (Map<String, dynamic> i in jsonDecode(response.body.toString())) {
        getTasks.add(Taskdropdown.fromJson(i));
      }
    }
  }

  static Future<dynamic> gettaskCategory(int accid) async {
    var body = {
      "account_id": accid.toString(),
    };

    Uri url = Uri.parse("${baseurl}fetch_task_categories?");

    final response = await http.post(url, body: body);

    if (response.statusCode == 200) {
      myCategories.clear();

      for (Map<String, dynamic> i in jsonDecode(response.body.toString())) {
        myCategories.add(CategorysDropdown.fromJson(i));
      }
    }
  }

  static Future<void> getCollborators(int accid, int projectid) async {
    var body = {
      "account_id": accid.toString(),
      "project_id": [projectid]
    };

    Uri url = Uri.parse("${baseurl}fetch_users_by_projects");

    try {
      final response = await http.post(
        url,
        headers: {
          'Content-Type': 'application/json',
        },
        body: jsonEncode(body),
      );

      if (response.statusCode == 200) {
        collboraotrs.clear();

        for (Map<String, dynamic> i in jsonDecode(response.body.toString())) {
          collboraotrs.add(CollaboratorsDropdown.fromJson(i));
          print(CollaboratorsDropdown.fromJson(i).firstName);
        }
      } else {
        print('Failed to load data. Status code: ${response.statusCode}');
        print('Response body: ${response.body}');
      }
    } catch (e) {
      print('Error: $e');
    }

    // if (response.statusCode == 200) {
    //   collboraotrs.clear();

    //   for (Map<String, dynamic> i in jsonDecode(response.body.toString())) {
    //     collboraotrs.add(CollaboratorsDropdown.fromJson(i));
    //     print(CollaboratorsDropdown.fromJson(i).firstName);
    //   }
    // }
  }

  static Future<dynamic> getUsersByTask(int accid, List<int> projectid) async {
    Uri url = Uri.parse("${baseurl}fetch_users_by_projects");

    var body = jsonEncode({
      "account_id": accid.toString(),
      "project_id": projectid,
    });

    final response = await http.post(url, body: jsonEncode(body));
    if (response.statusCode == 200) {
      print(jsonDecode(response.body.toString()));
      print(body.runtimeType);
    } else {
      print(response.statusCode);
    }
  }

  static Future<void> getTimesheetbyTask(int accid, int taskid) async {
    Uri url = Uri.parse("${baseurl}fetch_timesheet_by_task?");

    var body = {
      "account_id": accid.toString(),
      "task_id": taskid.toString(),
    };

    final response = await http.post(url, body: body);
    if (response.statusCode == 200) {
      timeSheet.clear();

      for (Map<String, dynamic> i in jsonDecode(response.body.toString())) {
        timeSheet.add(TimeSheetPojo.fromJson(i));
      }
    } else {}
  }

  static Future<bool> addTimeSheetOfProject(
      int project_task_id,
      int accid,
      int projectid,
      String startdate,
      String enddate,
      int taskStatus,
      int prorityid,
      int assignedto,
      int createdBy,
      String taskdesc,
      String reported_date,
      String comment,
      String startTime,
      String endTime) async {
    var body = {
      "project_task_id": project_task_id,
      "account_id": accid,
      "project_id": projectid,
      "act_start_date": startdate,
      "act_end_date": enddate,
      "task_status": taskStatus,
      "priority_id": prorityid,
      "assinged_to": assignedto,
      "created_by": createdBy,
      "task_desc": taskdesc,
      "reported_date": reported_date,
      "reported_time": null,
      "comment": comment,
      "start_time": startTime,
      "end_time": endTime
    };
    print("Request body: ${jsonEncode(body)}");
    Uri url = Uri.parse("${baseurl}update_project_task_by_user?");
    http.Response response = await http.post(
      url,
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(body),
    );
// print(body)

    if (response.statusCode == 200) {
      print("okkk added");
      print(response.body);
      return true;
    } else {
      print(response.body);
      return false;
    }
  }

  static Future<List<SnozzedClassPojo>> getSnoozedData() async {
    List<SnozzedClassPojo> snoozedData = [];
    var pref = await SharedPreferences.getInstance();
    var body = {
      "account_id": pref.getInt('account_id').toString(),
      "user_id": pref.getInt('user_id').toString(),
      "role_id": pref.getInt('role_id').toString(),
    };

    Uri url = Uri.parse("${baseurl}fetch_snooze_task");

    final response = await http.post(url, body: body);

    for (Map<String, dynamic> i in jsonDecode(response.body)) {
      snoozedData.add(SnozzedClassPojo.fromJson(i));
    }

    return snoozedData;
  }

  static Future<List<EnquiresPojo>> getEnquireCard(
      String id,
      List<int> enqids,
      List<int> assigned,
      List<ValueItem> enqsource,
      List<ValueItem> enqType,
      String createdDatefrom,
      String createdDateto,
      String updatedfromdate,
      String updatedtodate,
      String enqfromdate,
      String enqtodate,
      String enqCount) async {
    List<EnquiresPojo> enquireData = [];
    DateTime dateTime = DateTime.now();
    String date = "${dateTime.month}/${dateTime.day}/${dateTime.year}";

    // Extract the value properties from the ValueItem objects
    List<int> enqTypeIds = enqType.map((e) => e.value as int).toList();
    List<int> enqSourceIds = enqsource.map((e) => e.value as int).toList();

    Map<String, dynamic> requestBody = {
      "account_id": id,
      "enquiry_status_id": enqids.isEmpty ? null : enqids,
      "assigned_to": assigned.isEmpty ? null : assigned,
      "enquiry_sources": enqSourceIds.isEmpty ? null : enqSourceIds,
      "enquiry_type": enqTypeIds.isEmpty ? null : enqTypeIds,
      "created_from_date":
          createdDatefrom.isEmpty ? "09/24/2022" : createdDatefrom,
      "created_to_date": createdDateto.isEmpty ? date : createdDateto,
      "updated_from_date": updatedfromdate.isEmpty ? null : updatedfromdate,
      "updated_to_date": updatedtodate.isEmpty ? null : updatedtodate,
      "enquiry_from_date": enqfromdate.isEmpty ? null : enqfromdate,
      "enquiry_to_date": enqtodate.isEmpty ? null : enqtodate,
      "enq_count": "50"
    };
    print(requestBody);

    try {
      String jsonBody = jsonEncode(requestBody);
      Uri url = Uri.parse("${baseurl}filtered_enquiries");
      http.Response response = await http.post(
        url,
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonBody,
      );

      print("json Body: $jsonBody");
      print("Response Status: ${response.statusCode}");
      print("Response Body: ${response.body}");

      if (response.statusCode == 200) {
        List<dynamic> jsonData = jsonDecode(response.body);
        for (Map<String, dynamic> item in jsonData) {
          enquireData.add(EnquiresPojo.fromJson(item));
        }
      } else {
        print('Failed to load enquiries');
      }
    } catch (e) {
      print(e);
    }

    return enquireData;
  }

  static String customJsonEncode(Object object) {
    if (object == null) {
      return 'null';
    }
    return json.encode(object);
  }

  static Future<String> addEnquireCall(
      String fname,
      String lname,
      String phone,
      String email,
      String state,
      String city,
      String enq_detail_msg,
      String whatsapp_no,
      String company_name,
      String created_by,
      String account_id,
      String enquiry_date,
      String data_source,
      String address,
      String enquiry_type_id,
      String applicant_type_id,
      String enquiry_mode_id,
      String lead_level_id,
      String enquiry_status_id,
      String assigned_to,
      String estimated_closure_date,
      String next_appointment_date,
      String notes) async {
    // Helper function to handle null values
    dynamic encodeValue(dynamic value) {
      return value.isEmpty ? null : value;
    }

    var requestBody = {
      "fname": encodeValue(fname),
      "lname": encodeValue(lname),
      "phone": encodeValue(phone),
      "email": encodeValue(email),
      "state": encodeValue(state),
      "city": encodeValue(city),
      "pan_number": "",
      "enq_detail_msg": encodeValue(enq_detail_msg),
      "whatsapp_no": encodeValue(whatsapp_no),
      "loan_amount": "",
      "company_name": encodeValue(company_name),
      "pin": "",
      "created_by": encodeValue(created_by),
      "account_id": encodeValue(account_id),
      "enquiry_date": encodeValue(enquiry_date),
      "loan_type": "",
      "data_source": encodeValue(data_source),
      "address": encodeValue(address),
      "enquiry_type_id": encodeValue(enquiry_type_id),
      "applicant_type_id": encodeValue(applicant_type_id),
      "enquiry_mode_id": encodeValue(enquiry_mode_id),
      "lead_level_id": encodeValue(lead_level_id),
      "enquiry_status_id": encodeValue(enquiry_status_id),
      "assigned_to": encodeValue(assigned_to),
      "estimated_closure_date": encodeValue(estimated_closure_date),
      "next_appointment_date": encodeValue(next_appointment_date),
      "notes": encodeValue(notes),
    };

    print(customJsonEncode(requestBody));

    try {
      Uri url = Uri.parse("${baseurl}add_enquiry");
      http.Response response = await http.post(
        url,
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: customJsonEncode(requestBody), // Encode the body as JSON
      );

      print(response.body);

      return jsonDecode(response.body)['message'];
    } catch (e) {
      print(e);
      return "Something Went Wrong";
    }
  }

  static Future<GetAllDropdownEnquire> getAllDropDOwnsEnquire() async {
    var pref = await SharedPreferences.getInstance();
    Uri url = Uri.parse(
        "${baseurl}enquiry_dropdown/${pref.getInt('account_id') ?? 1}");

    final response = await http.get(url);

    print(response.body);

    return GetAllDropdownEnquire.fromJson(jsonDecode(response.body));
  }

  static Future<GetAllDataofEnquire> getFullDataOfEnquire(int id) async {
    Uri url = Uri.parse("${baseurl}enquiry_details");

    final response = await http.post(url, body: {
      "enquiry_id": "${id}",
    });

    print("-------------55--------------");
    print(response.body);
    print("-------------66--------------");
    return GetAllDataofEnquire.fromJson(jsonDecode(response.body)[0]);
  }

  static Future<String> postEnquireCOmments(
      String SendtoCustomer,
      String Enqid,
      String followupdate,
      String commentStatusid,
      String profilepath,
      String message,
      String createdby,
      String accountid) async {
    Uri url = Uri.parse("${baseurl}add_commentlog");

    var body = {
      "send_to_customer": SendtoCustomer,
      "enquiry_id": Enqid,
      "follow_up_date": followupdate,
      "comment_status_id": commentStatusid,
      "profile_path": profilepath,
      "message": message,
      "created_by": createdby,
      "account_id": accountid
    };
    final response = await http.post(url, body: body);

    return (jsonDecode(response.body)['message']);
  }

  static Future<List<EnquiresCommentss>> getEnquireComment(
      String accid, String enqid) async {
    List<EnquiresCommentss> enquireComment = [];
    try {
      Uri url = Uri.parse("${baseurl}fetch_comment_log");
      print(accid);
      print(enqid);

      var body = {"account_id": accid, "enquiry_id": enqid};

      final response = await http.post(url, body: body);

      print(response.body);

      for (Map<String, dynamic> i in jsonDecode(response.body)) {
        enquireComment.add(EnquiresCommentss.fromJson(i));
      }
      return enquireComment;
    } on Exception catch (e) {
      print(e);
      return enquireComment;
    } catch (e) {
      print(e);
      return enquireComment;
    }
  }

  static Future<List<dynamic>> fetchProjects(int statusGroupId) async {
    final sharedPref = await SharedPreferences.getInstance();
    int? userId = sharedPref.getInt('user_id');
    int? accountId = sharedPref.getInt('account_id');

    if (userId == null || accountId == null) {
      throw Exception('User ID or Account ID not found in Shared Preferences');
    }

    Uri uri = Uri.parse('${baseurl}fetch_projects');
    var body = jsonEncode({
      'user_id': userId,
      'account_id': accountId,
      'status_group_id': statusGroupId
    });

    final response = await http.post(uri, body: body, headers: {
      'Content-Type': 'application/json',
    });

    if (response.statusCode == 200) {
      List<dynamic> data = jsonDecode(response.body);
      return data;
    } else {
      throw Exception('Failed to load projects');
    }
  }

  static Future<List<Map<String, dynamic>>> fetchEmployees(
      String accountId) async {
    final response = await http.post(
      Uri.parse('${baseurl}/fetch_account_employee'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
      }),
    );

    if (response.statusCode == 200) {
      List<dynamic> data = jsonDecode(response.body);
      List<Map<String, dynamic>> employees = [];
      data.forEach((employee) {
        employees.add({
          'first_name': employee['first_name'],
          'last_name': employee['last_name'],
          'user_id': employee['user_id'],
        });
      });
      return employees;
    } else {
      throw Exception('Failed to fetch employees');
    }
  }

  static Future<bool> addDailyPlan(Map<String, dynamic> planData) async {
    final response = await http.post(
      headers: {
        'Content-Type': 'application/json',
      },
      Uri.parse('${baseurl}add_daily_plan'),
      body: jsonEncode(planData),
    );
    print(response.body);

    if (response.statusCode == 200) {
      final responseBody = json.decode(response.body);

      return responseBody['success'];
    } else {
      throw Exception('Failed to insert data');
    }
  }

  static Future<bool> updateDailyPlan(Map<String, dynamic> planData) async {
    try {
      final response = await http.post(
        Uri.parse('${baseurl}update_daily_plan'),
        headers: {
          'Content-Type': 'application/json',
        },
        body: jsonEncode(planData),
      );

      if (response.statusCode == 200) {
        final responseBody = json.decode(response.body);
        print('Response Body: $responseBody');
        return responseBody['success'];
      } else {
        print('Failed to update data. Status code: ${response.statusCode}');
        print('Response Body: ${response.body}');
        return false;
      }
    } catch (error) {
      print('Error occurred: $error');
      throw Exception('Failed to update data: $error');
    }
  }

  static Future<bool> addTaskData(Map<String, dynamic> planData) async {
    final response = await http.post(
      Uri.parse('${baseurl}/update_daily_plan'),
      body: planData,
    );

    if (response.statusCode == 200) {
      final responseBody = json.decode(response.body);

      return responseBody['success'];
    } else {
      throw Exception('Failed to insert data');
    }
  }

  static Future<List<Map<String, dynamic>>> fetchAttendance(
      DateTime date, String? teamId) async {
    final response = await http.post(
      Uri.parse('${baseurl}fetch_all_attendance'),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({
        'account_id': '1100',
        'team_id': teamId,
      }),
    );

    if (response.statusCode == 200) {
      final List<dynamic> data = jsonDecode(response.body);
      final String formattedDate =
          "${date.day.toString().padLeft(2, '0')}/${date.month.toString().padLeft(2, '0')}/${date.year}";

      print('Formatted Date: $formattedDate');
      print('API Response Data: $data');

      List<Map<String, dynamic>> attendanceList = [];

      for (var item in data) {
        print('Item: $item');

        DateTime createdAt = DateTime.parse(item['created_at']);
        String punchInDate =
            "${createdAt.day.toString().padLeft(2, '0')}/${createdAt.month.toString().padLeft(2, '0')}/${createdAt.year}";

        if (punchInDate == formattedDate) {
          attendanceList.add({
            'username': item['user_name'],
            'punchInTime': item['punch_in'] ?? '--',
            'punchOutTime': item['punch_out'] ?? '--',
            'totalHours': item['total_hours'] ?? '--',
          });
        }
      }

      print('Filtered Attendance List: $attendanceList');
      return attendanceList;
    } else {
      throw Exception('Failed to load attendance data');
    }
  }

  static Future<List<Map<String, dynamic>>> fetchTeams() async {
    final prefs = await SharedPreferences.getInstance();
    final userId = prefs.getInt('user_id') ?? 0;
    final roleId = prefs.getInt('role_id') ?? 0;

    final url = Uri.parse('${baseurl}fetch_teams');

    final response = await http.post(
      url,
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, int>{
        'user_id': userId,
        'role_id': roleId,
      }),
    );

    if (response.statusCode == 200) {
      List<dynamic> data = jsonDecode(response.body);
      return List<Map<String, dynamic>>.from(data);
    } else {
      throw Exception('Failed to load teams');
    }
  }

  static Future<void> updateProjectTaskByUser(Autogenerated cardData) async {
    Uri url = Uri.parse("${baseurl}update_project_task_by_user");

    try {
      // Print the card data being sent
      print(jsonEncode(cardData));

      // Make the POST request
      http.Response response = await http.post(
        url,
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(cardData),
      );

      // Print the response body for debugging
      print(response.body);

      // Decode the response body
      Map<String, dynamic> responseData = jsonDecode(response.body);

      // Check if the request was successful
      if (responseData['success'] == true) {
        // Send a success toast message
        Fluttertoast.showToast(
            msg: responseData['message'].isNotEmpty
                ? responseData['message']
                : 'Update successful',
            toastLength: Toast.LENGTH_LONG,
            gravity: ToastGravity.BOTTOM,
            timeInSecForIosWeb: 1,
            backgroundColor: Colors.grey.shade200.withOpacity(0.5),
            textColor: Colors.black,
            fontSize: 16.0);
      } else {
        // Handle the error message
        String errorMessage = responseData['message'].isNotEmpty
            ? responseData['message']
            : 'Unknown error occurred';
        Fluttertoast.showToast(
            msg: errorMessage,
            toastLength: Toast.LENGTH_LONG,
            gravity: ToastGravity.BOTTOM,
            timeInSecForIosWeb: 1,
            backgroundColor: Colors.redAccent,
            textColor: Colors.white,
            fontSize: 16.0);
      }
    } catch (e) {
      // Catch and handle any exceptions
      Fluttertoast.showToast(
          msg: 'Error: $e',
          toastLength: Toast.LENGTH_LONG,
          gravity: ToastGravity.BOTTOM,
          timeInSecForIosWeb: 1,
          backgroundColor: Colors.redAccent,
          textColor: Colors.white,
          fontSize: 16.0);
    }
  }
  // static Future<String> updateProjectTaskByUser(Autogenerated cardData) async {
  //   Uri url = Uri.parse("${baseurl}update_project_task_by_user");

  //   var body = {
  //     "account_id": cardData.accountId,
  //     "project_task_id": cardData.projectTaskId,
  //     "project_id": cardData.projectId,
  //     "task_type": cardData.taskType,
  //     "phase_id": cardData.phaseId,
  //     "task_name": cardData.taskName,
  //     "task_category": cardData.taskCategory,
  //     "est_start_date": cardData.estStartDate,
  //     "est_end_date": cardData.estEndDate,
  //     "plan_start_date": cardData.planStartDate,
  //     "plan_end_date": cardData.planEndDate,
  //     "act_start_date": cardData.actStartDate,
  //     "act_end_date": cardData.actEndDate,
  //     "task_status": cardData.taskStatus,
  //     "priority_id": cardData.priorityId,
  //     "sequence": cardData.sequence,
  //     "assinged_to": cardData.assingedTo,
  //     "collaborators_id": (cardData.collaborators ?? []).join(','),
  //     "est_efforts": cardData.estEfforts,
  //     "due_date": cardData.dueDate,
  //     "ext_efforts": "",
  //     "act_efforts": cardData.actEfforts,
  //     "start_time": cardData.startTime,
  //     "focus": cardData.focus,
  //     "invoiced": cardData.invoiced,
  //     "billable": cardData.billable,
  //     "snooze_task": cardData.snoozeTask,
  //     "snooze_date": cardData.snoozeDate,
  //     "edit_mode": cardData.editMode,
  //     "created_by": cardData.createdBy,
  //     "created_at": cardData.createdAt,
  //     "updated_by": cardData.updatedBy,
  //     "updated_at": cardData.updatedAt,
  //     "attachment": cardData.attachment,
  //     "task_desc": cardData.taskDesc,
  //     "ref_project_task_id": cardData.refProjectTaskId,
  //     "reported_date": cardData.reportedDate,
  //     "reported_time": cardData.reportedTime,
  //     "end_time": cardData.endTime,
  //     "assinged_name": cardData.assingedName,
  //     "my_efforts": cardData.myEfforts,
  //     "all_efforts": cardData.allEfforts,
  //     "task_day_ago": cardData.taskDayAgo,
  //     "project_name": cardData.projectName,
  //     "priority_name": cardData.priorityName,
  //     "task_type_name": cardData.taskTypeName,
  //     "task_category_name": cardData.taskCategoryName,
  //     "focus_id": cardData.focusId,
  //     "collaborators": cardData.collaborators,
  //     "status": cardData.status,
  //     "status_group": cardData.statusGroup
  //   };
  //   http.Response response = await http.post(
  //     url,
  //     headers: <String, String>{
  //       'Content-Type': 'application/json; charset=UTF-8',
  //     },
  //     body: jsonEncode(body),
  //   );

  //   print(response.body);

  //   return jsonDecode(response.body)['message'];
  // }

  static Future<void> fetchAndStoreEmployeeId(String accountId) async {
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      int? userId = prefs.getInt('user_id');

      if (userId == null) {
        print('User ID not found in SharedPreferences');
        return;
      }

      final response = await http.post(
        Uri.parse('${baseurl}fetch_employees'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, dynamic>{
          'account_id': accountId,
        }),
      );

      if (response.statusCode == 200) {
        final responseBody = json.decode(response.body);
        final employee = responseBody['users'].firstWhere(
          (user) => user['user_id'] == userId,
          orElse: () => null,
        );

        if (employee != null) {
          final String employeeId = employee['employee_id'].toString();
          await prefs.setString('employee_id', employeeId);

          print('Employee ID stored: $employeeId');
          print('Employee details: $employee');
        } else {
          print('Employee not found for user ID: $userId');
        }
      } else {
        print('Failed to fetch employees, status code: ${response.statusCode}');
        throw Exception('Failed to fetch employees');
      }
    } catch (e) {
      print('Error in fetchAndStoreEmployeeId: $e');
    }
  }

  static Future<List<Map<String, dynamic>>> fetchEmployeesDropdown(
      String accountId) async {
    try {
      final response = await http.post(
        Uri.parse('${baseurl}fetch_employees'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, dynamic>{
          'account_id': accountId,
        }),
      );

      if (response.statusCode == 200) {
        final responseBody = json.decode(response.body) as Map<String, dynamic>;

        if (responseBody.containsKey('users') &&
            responseBody['users'] is List) {
          List<dynamic> usersList = responseBody['users'] as List<dynamic>;

          // Convert each item in the list to a Map<String, dynamic>
          List<Map<String, dynamic>> employees =
              usersList.map((item) => item as Map<String, dynamic>).toList();
          return employees;
        } else {
          print('Invalid response structure: ${responseBody}');
          throw Exception('Invalid response structure');
        }
      } else {
        print('Failed to fetch employees, status code: ${response.statusCode}');
        throw Exception('Failed to fetch employees');
      }
    } catch (e) {
      print('Error in fetchEmployeesDropdown: $e');
      throw e;
    }
  }

  static Future<List<Map<String, dynamic>>> fetchLeaveTypes() async {
    final response = await http.post(Uri.parse(
        '${baseurl}fetch_leave_type')); // Replace with your actual API endpoint

    if (response.statusCode == 200) {
      final List<dynamic> leaveTypes = json.decode(response.body);
      return leaveTypes.map((leave) {
        return {
          'request_type_id': leave['request_type_id'],
          'request_type': leave['request_type'],
        };
      }).toList();
    } else {
      throw Exception('Failed to fetch leave types');
    }
  }

  static Future<Map<String, dynamic>> fetchLeaveBalance({
    required int accountId,
    required int employeeId,
    required int requestTypeId,
  }) async {
    final response = await http.post(
      Uri.parse(
          '${baseurl}fetch_leaves_of_employee'), // Replace with actual URL
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode({
        'account_id': accountId,
        'employee_id': employeeId,
        'request_type_id': requestTypeId,
      }),
    );

    if (response.statusCode == 200) {
      return jsonDecode(response.body);
    } else {
      throw Exception('Failed to fetch leave balance');
    }
  }

  static Future<void> addLeave({
    required int accountId,
    required int employeeId,
    required int requestTypeId,
    required int noOfDays,
    required String reason,
    required String dateFrom,
    required String dateTo,
    required String returnToOffice,
    required int createdBy,
    required String attachment,
  }) async {
    final url = Uri.parse('${baseurl}add_leave');

    var request = http.MultipartRequest('POST', url)
      ..fields['account_id'] = accountId.toString()
      ..fields['employee_id'] = employeeId.toString()
      ..fields['request_type_id'] = requestTypeId.toString()
      ..fields['no_of_days'] = noOfDays.toString()
      ..fields['reason'] = reason
      ..fields['date_from'] = dateFrom
      ..fields['date_to'] = dateTo
      ..fields['return_to_office'] = returnToOffice
      ..fields['created_by'] = createdBy.toString();

    if (attachment.isNotEmpty) {
      var file = await http.MultipartFile.fromPath('attachment', attachment);
      request.files.add(file);
    }
    print('Request Fields: ${request.fields}');
    if (request.files.isNotEmpty) {
      print('Request Files: ${request.files}');
    }
    try {
      var response = await request.send();

      if (response.statusCode == 200) {
        print('Leave request submitted successfully');
      } else {
        print(
            'Failed to submit leave request. Error: ${response.reasonPhrase}');
      }
    } catch (e) {
      print('Failed to submit leave request. Exception: $e');
    }
  }

  static Future<List<dynamic>> fetchAllLeave(String accountId) async {
    final response = await http.post(
      Uri.parse('${baseurl}fetch_all_leave'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
      }),
    );

    if (response.statusCode == 200) {
      return jsonDecode(response.body);
    } else {
      throw Exception('Failed to load leave data');
    }
  }

  static Future<List<LeaveHistory>> fetchSingleEmployeeLeave() async {
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      String? employeeId = prefs.getString('employee_id');

      if (employeeId == null) {
        throw Exception('Employee ID not found in SharedPreferences');
      }

      final response = await http.post(
        Uri.parse('${baseurl}fetch_single_employee_leave'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, dynamic>{
          'account_id': '1100',
          'employee_id': int.parse(employeeId),
        }),
      );

      if (response.statusCode == 200) {
        List jsonResponse = json.decode(response.body);
        List<String> requestTypeIds = [];
        for (var leave in jsonResponse) {
          requestTypeIds.add(leave['request_type_id'].toString());
        }
        await prefs.setStringList('request_type_ids', requestTypeIds);

        return jsonResponse
            .map((leave) => LeaveHistory.fromJson(leave))
            .toList();
      } else {
        throw Exception('Failed to load leave history');
      }
    } catch (e) {
      throw Exception('Failed to load leave history: $e');
    }
  }

  // static Future<Map<String, dynamic>> fetchTotalLeaves() async {
  //   SharedPreferences prefs = await SharedPreferences.getInstance();
  //   List<String> requestTypeIds = prefs.getStringList('request_type_ids') ?? [];

  //   final response = await http.post(
  //     Uri.parse(
  //         'https://pw-bms-dev.portalwiz.in/laravelapi/public/api/fetch_total_leaves'),
  //     headers: <String, String>{
  //       'Content-Type': 'application/json; charset=UTF-8',
  //     },
  //     body: jsonEncode(<String, dynamic>{
  //       'account_id': '1',
  //       'employee_id': 2,
  //       'request_type_id':
  //           requestTypeIds.isNotEmpty ? requestTypeIds.last : '0',
  //     }),
  //   );

  //   if (response.statusCode == 200) {
  //     Map<String, dynamic> responseData = json.decode(response.body);

  //     return responseData;
  //   } else {
  //     throw Exception('Failed to load total leaves');
  //   }
  // }

  static Future<void> updateLeaveStatus(
      String leaveId, String leaveStatusId, String comment) async {
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      String? employeeId = prefs.getString('employee_id');
      int? userId = prefs.getInt('user_id');

      if (employeeId == null) {
        throw Exception('Employee ID not found in SharedPreferences');
      }

      if (userId == null) {
        throw Exception('User ID not found in SharedPreferences');
      }

      final response = await http.post(
        Uri.parse('${baseurl}update_leave'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, dynamic>{
          'account_id': '1100',
          'leave_id': leaveId,
          'employee_id': int.parse(employeeId),
          'leave_status_id': leaveStatusId,
          'comment': comment,
          'updated_by': userId,
        }),
      );

      if (response.statusCode == 200) {
        print('Leave status updated!');
      } else {
        throw Exception('Failed to update leave status');
      }
    } catch (e) {
      throw Exception('Failed to update leave status: $e');
    }
  }

  static Future<void> addWFH({
    required String accountId,
    required int employeeId,
    required int noOfDays,
    required String reason,
    required String dateFrom,
    required String dateTo,
    required String returnToOffice,
    required int createdBy,
  }) async {
    final url = Uri.parse('${baseurl}add_wfh');
    final response = await http.post(
      url,
      body: jsonEncode({
        "account_id": accountId,
        "employee_id": employeeId,
        "no_of_days": noOfDays.toString(),
        "reason": reason,
        "date_from": dateFrom,
        "date_to": dateTo,
        "return_to_office": returnToOffice,
        "created_by": createdBy
      }),
      headers: {
        'Content-Type': 'application/json',
      },
    );

    if (response.statusCode == 200) {
      print('Work from home request submitted successfully.');
      print('Response: ${jsonDecode(response.body)}');
    } else {
      print('Failed to submit work from home request');
      print('Status code: ${response.statusCode}');
      print('Response: ${response.body}');
    }
  }

  static Future<List<dynamic>> fetchAllWFH(String accountId) async {
    final response = await http.post(
      Uri.parse('${baseurl}fetch_all_wfh'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
      }),
    );

    if (response.statusCode == 200) {
      return jsonDecode(response.body);
    } else {
      throw Exception('Failed to load work-from-home data');
    }
  }

  static Future<List<WfhHistory>> fetchSingleEmployeeWFH() async {
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      String? employeeId = prefs.getString('employee_id');

      if (employeeId == null) {
        throw Exception('Employee ID not found in SharedPreferences');
      }

      final response = await http.post(
        Uri.parse('${baseurl}fetch_single_employee_wfh'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, dynamic>{
          'account_id': '1100',
          'employee_id': int.parse(employeeId),
        }),
      );

      if (response.statusCode == 200) {
        List<dynamic> jsonResponse = json.decode(response.body);
        return jsonResponse.map((x) => WfhHistory.fromJson(x)).toList();
      } else {
        throw Exception('Failed to load WFH history');
      }
    } catch (e) {
      throw Exception('Failed to load WFH history: $e');
    }
  }

  static Future<void> updateWFHStatus(
      String wfhId, String status, String comment) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();

    String? employeeId = prefs.getString('employee_id');

    if (employeeId == null) {
      throw Exception('Employee ID not found in SharedPreferences');
    }

    final Map<String, dynamic> requestBody = {
      "account_id": "1100",
      "wfh_id": wfhId,
      "wfh_status": status,
      "comment": comment,
      "updated_by": employeeId,
    };

    print('Request Body: ${jsonEncode(requestBody)}');

    final response = await http.post(
      Uri.parse('${baseurl}update_wfh'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(requestBody),
    );

    if (response.statusCode == 200) {
      print('WFH status updated successfully');
    } else {
      print('Failed to update WFH status, status code: ${response.statusCode}');
      throw Exception('Failed to update WFH status');
    }
  }

  static Future<List<dynamic>> fetchApprovedLeaves(
      String accountId, String employeeId) async {
    final response = await http.post(
      Uri.parse('${baseurl}fetch_approved_leaves'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
        'employee_id': employeeId,
      }),
    );

    if (response.statusCode == 200) {
      return jsonDecode(response.body) as List<dynamic>;
    } else {
      throw Exception('Failed to fetch approved leaves');
    }
  }

  static Future<List<dynamic>> fetchDeniedLeaves(
      String accountId, String employeeId) async {
    final response = await http.post(
      Uri.parse('${baseurl}fetch_cancelled_leaves'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
        'employee_id': employeeId,
      }),
    );

    if (response.statusCode == 200) {
      return jsonDecode(response.body) as List<dynamic>;
    } else {
      throw Exception('Failed to fetch cancelled leaves');
    }
  }

  static Future<Map<String, dynamic>> fetchCasualLeaves() async {
    final headers = {
      'Content-Type': 'application/json',
    };

    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      String? employeeId = prefs.getString('employee_id');

      // Wait until employeeId is not null
      while (employeeId == null) {
        await Future.delayed(Duration(milliseconds: 100));
        employeeId = prefs.getString('employee_id');
      }

      final body = {
        "account_id": 1100,
        "employee_id": employeeId,
      };

      final response = await http.post(
        Uri.parse('${baseurl}fetch_casual_leaves'),
        headers: headers,
        body: json.encode(body),
      );

      if (response.statusCode == 200) {
        return json.decode(response.body);
      } else {
        throw Exception('Failed to fetch casual leaves');
      }
    } catch (e) {
      throw Exception('Failed to fetch casual leaves: $e');
    }
  }

  static Future<Map<String, dynamic>> fetchSickLeaves() async {
    final url =
        'https://pw-bms-dev.portalwiz.in/laravelapi/public/api/fetch_sick_leaves';
    final headers = {
      'Content-Type': 'application/json',
    };

    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      String? employeeId = prefs.getString('employee_id');

      // Wait until employeeId is not null
      while (employeeId == null) {
        await Future.delayed(Duration(milliseconds: 100));
        employeeId = prefs.getString('employee_id');
      }

      final body = {
        "account_id": 1100,
        "employee_id": int.parse(employeeId),
      };

      final response = await http.post(
        Uri.parse('${baseurl}fetch_sick_leaves'),
        headers: headers,
        body: json.encode(body),
      );

      if (response.statusCode == 200) {
        return json.decode(response.body);
      } else {
        throw Exception('Failed to fetch sick leaves');
      }
    } catch (e) {
      throw Exception('Failed to fetch sick leaves: $e');
    }
  }

  static Future<Map<String, dynamic>> fetchElectiveLeaves() async {
    final url =
        'https://pw-bms-dev.portalwiz.in/laravelapi/public/api/fetch_elective_leaves';
    final headers = {
      'Content-Type': 'application/json',
    };

    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      String? employeeId = prefs.getString('employee_id');

      // Wait until employeeId is not null
      while (employeeId == null) {
        await Future.delayed(Duration(milliseconds: 100));
        employeeId = prefs.getString('employee_id');
      }

      final body = {
        "account_id": 1100,
        "employee_id": int.parse(employeeId),
      };

      final response = await http.post(
        Uri.parse('${baseurl}fetch_elective_leaves'),
        headers: headers,
        body: json.encode(body),
      );

      if (response.statusCode == 200) {
        return json.decode(response.body);
      } else {
        throw Exception('Failed to fetch elective leaves');
      }
    } catch (e) {
      throw Exception('Failed to fetch elective leaves: $e');
    }
  }

  static Future<List<dynamic>> fetchApprovedWfh(
      String accountId, String employeeId) async {
    final response = await http.post(
      Uri.parse('${baseurl}fetch_approved_wfh'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
        'employee_id': employeeId,
      }),
    );

    if (response.statusCode == 200) {
      return jsonDecode(response.body) as List<dynamic>;
    } else {
      throw Exception('Failed to fetch approved wfh');
    }
  }

  static Future<List<dynamic>> fetchDeniedWfh(
      String accountId, String employeeId) async {
    final response = await http.post(
      Uri.parse('${baseurl}fetch_cancelled_wfh'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
        'employee_id': employeeId,
      }),
    );

    if (response.statusCode == 200) {
      return jsonDecode(response.body) as List<dynamic>;
    } else {
      throw Exception('Failed to fetch cancelled wfh');
    }
  }

  static Future<List<Map<String, dynamic>>> fetchProjectTypes(
      String accountId) async {
    final response = await http.post(
      Uri.parse(
          'https://portalwiz.net/laravelapi/public/api/fetch_project_types'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
      }),
    );

    if (response.statusCode == 200) {
      List<dynamic> data = jsonDecode(response.body);
      return data.map((item) => item as Map<String, dynamic>).toList();
    } else {
      throw Exception('Failed to fetch project types');
    }
  }

  static Future<List<Map<String, dynamic>>> fetchProjectOwners(
      String accountId) async {
    final response = await http.post(
      Uri.parse(
          'https://portalwiz.net/laravelapi/public/api/fetch_account_users'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
      }),
    );

    if (response.statusCode == 200) {
      return List<Map<String, dynamic>>.from(jsonDecode(response.body));
    } else {
      throw Exception('Failed to fetch project owners');
    }
  }

  static Future<List<Map<String, dynamic>>> fetchCompanies(
      String accountId) async {
    final response = await http.post(
      Uri.parse('https://portalwiz.net/laravelapi/public/api/fetch_companies'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
      }),
    );

    if (response.statusCode == 200) {
      return List<Map<String, dynamic>>.from(jsonDecode(response.body));
    } else {
      throw Exception('Failed to fetch project companies');
    }
  }

  static Future<List<Map<String, dynamic>>> fetchProjectStatus(
      String accountId) async {
    final response = await http.post(
      Uri.parse(
          'https://portalwiz.net/laravelapi/public/api/fetch_project_status'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
      body: jsonEncode(<String, String>{
        'account_id': accountId,
      }),
    );

    if (response.statusCode == 200) {
      return List<Map<String, dynamic>>.from(jsonDecode(response.body));
    } else {
      throw Exception('Failed to fetch project status');
    }
  }

  static Future<List<Map<String, dynamic>>> fetchPriority() async {
    final response = await http.get(
      Uri.parse('https://portalwiz.net/laravelapi/public/api/fetch_priority'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
    );

    if (response.statusCode == 200) {
      return List<Map<String, dynamic>>.from(jsonDecode(response.body));
    } else {
      throw Exception('Failed to fetch project priority');
    }
  }

  static Future<bool> addProject(Map<String, dynamic> projectData) async {
    final url = 'https://portalwiz.net/laravelapi/public/api/add_project';
    final headers = {'Content-Type': 'application/json'};
    final body = jsonEncode(projectData);
    print(projectData);

    final response =
        await http.post(Uri.parse(url), headers: headers, body: body);

    if (response.statusCode == 200) {
      final responseData = jsonDecode(response.body);
      return responseData['success'];
    } else {
      throw Exception('Failed to add project');
    }
  }

  static Future<void> addProjectTasksByUser({
    required int accountId,
    required int roleId,
    required int userId,
    required int projectTaskId,
    required int? assigneeId,
    int? collaboratorId,
    required int lkFeedbackId,
    required int smileyId,
    required String comment,
  }) async {
    final url = Uri.parse('${baseurl}add_feedback_to_project_task');

    final Map<String, dynamic> requestBody = {
      'account_id': "$accountId",
      'role_id': "$roleId",
      'user_id': "$userId",
      'project_task_id': "$projectTaskId",
      'assignee_id': (assigneeId == null) ? null : "$assigneeId",
      'collaborator_id': (collaboratorId == null) ? null : "$collaboratorId",
      'lk_feedback_id': "$lkFeedbackId",
      'smiley_id': "$smileyId",
      'comment': comment,
    };
    print(requestBody);

    try {
      final response = await http.post(
        url,
        headers: {
          'Content-Type': 'application/json',
        },
        body: json.encode(requestBody),
      );

      if (response.statusCode == 200) {
        // Handle the response as needed
        print('Response data: ${response.body}');
      } else {
        print(
            'Failed to fetch project tasks. Status code: ${response.statusCode}');
      }
    } catch (e) {
      print('Error occurred: $e');
    }
  }

  static Future<Map<String, dynamic>> fetchCountfordate() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    try {
      final response =
          await http.post(Uri.parse("${baseurl}fetch_daily_plan_count"), body: {
        "user_id": "${prefs.getInt("user_id")}",
        "plan_date":
            "${DateTime.now().year}-${DateTime.now().month}-${DateTime.now().day}"
      });
      print(response.body);
      if (response.statusCode == 200) {
        print(jsonDecode(response.body));
        return jsonDecode(response.body);
      }
      return {};
    } catch (e) {
      print(e);
      return {};
    }
  }

  static Future<List<Map<String, dynamic>>> filterTaskTypeDropDown() async {
    List<Map<String, dynamic>> data = [];

    try {
      final response = await http.get(Uri.parse("${baseurl}fetch_task_types"));

      if (response.statusCode == 200) {
        for (Map<String, dynamic> a in jsonDecode(response.body)) {
          data.add(a);
        }
      } else {
        // Handle the case when the server does not return a 200 status code
        print('Failed to load task types. Status code: ${response.statusCode}');
      }
    } catch (e) {
      // Handle any exceptions that occur during the request
      print('Error fetching task types: $e');
    }

    return data;
  }

  static Future<List<Map<String, dynamic>>> filterTaskCategoryDropDown() async {
    List<Map<String, dynamic>> data = [];
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    try {
      final response = await http.post(
          Uri.parse("${baseurl}fetch_task_categories"),
          body: {"account_id": "${sharedPreferences.getInt("account_id")}"});

      if (response.statusCode == 200) {
        print(response.body);
        for (Map<String, dynamic> a in jsonDecode(response.body)) {
          data.add(a);
        }
      } else {
        // Handle the case when the server does not return a 200 status code
        print('Failed to load task types. Status code: ${response.statusCode}');
      }
    } catch (e) {
      // Handle any exceptions that occur during the request
      print('Error fetching task types: $e');
    }

    return data;
  }

  static Future<List<Map<String, dynamic>>>
      filterTaskCreatedByDropDown() async {
    List<Map<String, dynamic>> data = [];

    try {
      final response = await http.get(Uri.parse("${baseurl}fetch_created_by"));

      if (response.statusCode == 200) {
        for (Map<String, dynamic> a in jsonDecode(response.body)) {
          data.add(a);
        }
      } else {
        // Handle the case when the server does not return a 200 status code
        print('Failed to load task types. Status code: ${response.statusCode}');
      }
    } catch (e) {
      // Handle any exceptions that occur during the request
      print('Error fetching task types: $e');
    }

    return data;
  }

  static Future<List<Map<String, dynamic>>> filterProjectTypeDropDown() async {
    List<Map<String, dynamic>> data = [];
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    try {
      final response = await http.post(
          Uri.parse("${baseurl}fetch_project_types"),
          body: {"account_id": "${sharedPreferences.getInt("account_id")}"});

      if (response.statusCode == 200) {
        for (Map<String, dynamic> a in jsonDecode(response.body)) {
          data.add(a);
        }
      } else {
        // Handle the case when the server does not return a 200 status code
        print(
            'Failed to load project types. Status code: ${response.statusCode}');
      }
    } catch (e) {
      // Handle any exceptions that occur during the request
      print('Error fetching project types: $e');
    }

    return data;
  }

  static Future<List<Map<String, dynamic>>> filterProjectNameDropDown(
      {int? projectTypeId}) async {
    List<Map<String, dynamic>> data = [];
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    try {
      // Print the projectTypeId and account_id for debugging
      print("Project Type ID: $projectTypeId");
      print("Account ID: ${sharedPreferences.getInt("account_id")}");

      final response = await http.post(
        Uri.parse("${baseurl}fetch_project_by_type"),
        body: {
          "account_id": "${sharedPreferences.getInt("account_id")}",
          "project_type_id":
              projectTypeId != null ? projectTypeId.toString() : '',
        },
      );

      // Print the response body for debugging
      print('Response Body: ${response.body}');

      if (response.statusCode == 200) {
        List<dynamic> responseData = jsonDecode(response.body);

        // Check if responseData is a list
        if (responseData is List) {
          for (Map<String, dynamic> a in responseData) {
            data.add(a);
          }
        } else {
          print('Unexpected response format');
        }
      } else {
        print(
            'Failed to load project names. Status code: ${response.statusCode}');
      }
    } catch (e) {
      print('Error fetching project names: $e');
    }

    return data;
  }

  static Future<List<Map<String, dynamic>>> filterAssigneeDropDown() async {
    List<Map<String, dynamic>> data = [];
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    try {
      final response = await http.post(
          Uri.parse("${baseurl}fetch_account_users"),
          body: {"account_id": "${sharedPreferences.getInt("account_id")}"});

      if (response.statusCode == 200) {
        for (Map<String, dynamic> a in jsonDecode(response.body)) {
          data.add(a);
        }
      } else {
        // Handle the case when the server does not return a 200 status code
        print(
            'Failed to load project assignee. Status code: ${response.statusCode}');
      }
    } catch (e) {
      // Handle any exceptions that occur during the request
      print('Error fetching project assignee: $e');
    }

    return data;
  }

  static Future<List<Map<String, dynamic>>> filterTaskStatusDropDown() async {
    List<Map<String, dynamic>> data = [];
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    try {
      final response = await http.post(Uri.parse("${baseurl}fetch_task_status"),
          body: {"account_id": "${sharedPreferences.getInt("account_id")}"});

      if (response.statusCode == 200) {
        for (Map<String, dynamic> a in jsonDecode(response.body)) {
          data.add(a);
        }
      } else {
        // Handle the case when the server does not return a 200 status code
        print(
            'Failed to load project assignee. Status code: ${response.statusCode}');
      }
    } catch (e) {
      // Handle any exceptions that occur during the request
      print('Error fetching project assignee: $e');
    }

    return data;
  }

  static Future<List<Map<String, String>>> fetchCompanyTypes() async {
    final response = await http.get(Uri.parse("${baseurl}fetch_company_type"));
    if (response.statusCode == 200) {
      List data = json.decode(response.body);
      return data.map<Map<String, String>>((item) {
        return {
          "company_type_id": item["company_type_id"].toString(),
          "company_type": item["company_type"],
        };
      }).toList();
    } else {
      throw Exception('Failed to load company types');
    }
  }

  static Future<List<Map<String, String>>> fetchCompanyStatus() async {
    final response =
        await http.get(Uri.parse("${baseurl}fetch_company_status"));
    if (response.statusCode == 200) {
      List data = json.decode(response.body);
      return data.map<Map<String, String>>((item) {
        return {
          "company_status_id": item["company_status_id"].toString(),
          "company_status": item["company_status"],
        };
      }).toList();
    } else {
      throw Exception('Failed to load company status');
    }
  }

  static Future<Map<String, dynamic>> addCompany(
      Map<String, String?> companyData) async {
    final url = Uri.parse('${baseurl}add_companies');
    print('Request Body: ${json.encode(companyData)}');
    try {
      final response = await http.post(
        url,
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        body: json.encode(companyData),
      );
      print('Response Body: ${response.body}');
      if (response.statusCode == 200) {
        return json.decode(response.body);
      } else {
        // Handle different status codes if needed
        return {
          'success': false,
          'message':
              'Failed to add company. Status code: ${response.statusCode}',
        };
      }
    } catch (e) {
      // Handle any errors that occur during the request
      return {
        'success': false,
        'message': 'An error occurred: $e',
      };
    }
  }

  Future<List<Map<String, dynamic>>> fetchCompany() async {
    final response = await http.post(
      Uri.parse(
          'https://pw-bms-dev.portalwiz.in/laravelapi/public/api/fetch_companies'),
      body: jsonEncode({"account_id": "1100"}),
      headers: {"Content-Type": "application/json"},
    );

    if (response.statusCode == 200) {
      List<dynamic> companies = jsonDecode(response.body);
      return companies
          .map((company) => company as Map<String, dynamic>)
          .toList();
    } else {
      throw Exception('Failed to load companies');
    }
  }

  Future<List<Contact>> fetchContacts(String accountId) async {
    final response = await http.post(
      Uri.parse('${baseurl}fetch_contacts'),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({'account_id': accountId}),
    );

    if (response.statusCode == 200) {
      List<dynamic> data = jsonDecode(response.body);
      return data.map((contact) => Contact.fromJson(contact)).toList();
    } else {
      throw Exception('Failed to load contacts');
    }
  }

  static Future<Map<String, dynamic>> addContact(
      Map<String, dynamic> contactData) async {
    final response = await http.post(
      Uri.parse('${baseurl}add_contact'),
      headers: {
        'Content-Type': 'application/json',
      },
      body: jsonEncode(contactData),
    );

    if (response.statusCode == 200) {
      return jsonDecode(response.body);
    } else {
      throw Exception('Failed to add contact');
    }
  }

  static Future<List<String>> fetchEmployeeTypes() async {
    final response = await http.get(
      Uri.parse('${baseurl}employee_type_dropdown'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
    );

    if (response.statusCode == 200) {
      final List<dynamic> data = jsonDecode(response.body);
      return data.map((item) => item['employment_type'] as String).toList();
    } else {
      throw Exception('Failed to load employee types');
    }
  }

  static Future<List<String>> fetchUsernames() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final roleId = prefs.getInt('role_id');

      if (roleId == null) {
        throw Exception('Role ID not found in SharedPreferences.');
      }

      final response = await http.post(
        Uri.parse('${baseurl}fetch_users'),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, int>{'role_id': roleId}),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        if (data is List) {
          List<String> usernames = [];
          for (var user in data) {
            // Ensure 'username' field is checked and converted to String
            final username = user['username'];
            if (username is String && username.isNotEmpty) {
              usernames.add(username);
            }
          }
          return usernames;
        } else {
          throw Exception(
              'Failed to fetch usernames. Invalid response format.');
        }
      } else {
        throw Exception(
            'Failed to load data. Status code: ${response.statusCode}');
      }
    } catch (e) {
      throw Exception('Failed to fetch usernames: $e');
    }
  }

  static Future<List<String>> fetchDesignationDropdown() async {
    final response = await http.get(
      Uri.parse('${baseurl}designation_dropdown'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
    );

    if (response.statusCode == 200) {
      final List<dynamic> data = jsonDecode(response.body);
      return data.map((item) => item['designation'] as String).toList();
    } else {
      throw Exception('Failed to load designation');
    }
  }

  static Future<List<String>> fetchDepartmentDropdown() async {
    final response = await http.get(
      Uri.parse('${baseurl}department_dropdown'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
    );

    if (response.statusCode == 200) {
      final List<dynamic> data = jsonDecode(response.body);
      return data.map((item) => item['department'] as String).toList();
    } else {
      throw Exception('Failed to load department');
    }
  }

  static Future<List<String>> fetchManagerDropdown() async {
    final response = await http.get(
      Uri.parse('${baseurl}reporting_manager_dropdown'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
    );

    if (response.statusCode == 200) {
      final List<dynamic> data = jsonDecode(response.body);
      return data.map((item) => item['employee_name'] as String).toList();
    } else {
      throw Exception('Failed to load manager');
    }
  }

  static Future<List<String>> fetchActiveStatusDropdown() async {
    final response = await http.get(
      Uri.parse('${baseurl}featch_active_statuses'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
    );

    if (response.statusCode == 200) {
      final List<dynamic> data = jsonDecode(response.body);
      return data.map((item) => item['status'] as String).toList();
    } else {
      throw Exception('Failed to load manager');
    }
  }

  static Future<List<String>> fetchGenderDropdown() async {
    final response = await http.get(
      Uri.parse('${baseurl}gender_dropdown'),
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
      },
    );

    if (response.statusCode == 200) {
      final List<dynamic> data = jsonDecode(response.body);
      return data.map((item) => item['gender'] as String).toList();
    } else {
      throw Exception('Failed to load gender');
    }
  }

  static Future<Map<String, dynamic>> fetchSingletask(int projectTaskId) async {
    Map<String, dynamic> data = {};
    SharedPreferences sharedPreferences = await SharedPreferences.getInstance();
    print({
      "account_id": "${sharedPreferences.getInt("account_id")}",
      "project_task_id": "${projectTaskId}"
    });
    try {
      final response = await http
          .post(Uri.parse("${baseurl}fetch_single_project_task"), body: {
        "account_id": "${sharedPreferences.getInt("account_id")}",
        "project_task_id": "${projectTaskId}"
      });

      if (response.statusCode == 200) {
        data = jsonDecode(response.body).first;
      } else {
        // Handle the case when the server does not return a 200 status code
        print('Failed to load task types. Status code: ${response.statusCode}');
      }
    } catch (e) {
      // Handle any exceptions that occur during the request
      print('Error fetching task types: $e');
    }

    return data;
  }
}
